In [ ]:
!git clone https://github.com/nehaaziya/resume-sreening-and-skill-matching-2.git

Cloning into 'resume-sreening-and-skill-matching-2'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 32 (delta 6), reused 23 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (32/32), 45.14 KiB | 11.28 MiB/s, done.
Resolving deltas: 100% (6/6), done.

In [ ]:
%cd resume-sreening-and-skill-matching-2

/content/resume-sreening-and-skill-matching-2

In [ ]:
!pip install sentence-transformers faiss-cpu pypdf python-docx scikit-learn

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Collecting faiss-cpu
  Downloading faiss_cpu-1.15.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Collecting pypdf
  Downloading pypdf-6.19.0-py3-none-any.whl.metadata (7.5 kB)
Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.16.1)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.29.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from faiss-cpu) (26.3)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from python-docx) (6.1.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.32.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading faiss_cpu-1.15.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 73.7 MB/s eta 0:00:00
Downloading pypdf-6.19.0-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 30.9 MB/s eta 0:00:00
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 20.3 MB/s eta 0:00:00
Installing collected packages: python-docx, pypdf, faiss-cpu
Successfully installed faiss-cpu-1.15.1 pypdf-6.19.0 python-docx-1.2.0

In [ ]:
!python run_demo.py

usage: run_demo.py [-h] --resumes_dir RESUMES_DIR
                   --job_description JOB_DESCRIPTION [--top_k TOP_K]
                   [--min_similarity MIN_SIMILARITY]
                   [--min_years_experience MIN_YEARS_EXPERIENCE]
                   [--min_education {None,High School,Associate,Bachelors,Masters,PhD}]
                   [--save_index_to SAVE_INDEX_TO]
run_demo.py: error: the following arguments are required: --resumes_dir, --job_description

In [ ]:
# Clone the existing GitHub project

!git clone https://github.com/nehaaziya/resume-sreening-and-skill-matching-2.git

Cloning into 'resume-sreening-and-skill-matching-2'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 32 (delta 6), reused 23 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (32/32), 45.14 KiB | 6.45 MiB/s, done.
Resolving deltas: 100% (6/6), done.

In [ ]:
# Move into the project directory

%cd resume-sreening-and-skill-matching-2

/content/resume-sreening-and-skill-matching-2/resume-sreening-and-skill-matching-2

In [ ]:
# Install required Python packages

!pip install -r requirements.txt

Requirement already satisfied: sentence-transformers>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 1)) (5.7.0)
Requirement already satisfied: faiss-cpu>=1.8.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 2)) (1.15.1)
Requirement already satisfied: torch>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 3)) (2.11.0+cpu)
Requirement already satisfied: spacy>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 4)) (3.8.16)
Collecting pdfplumber>=0.11.0 (from -r requirements.txt (line 5))
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 172.8 kB/s eta 0:00:00
Requirement already satisfied: python-docx>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: fastapi>=0.111.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 7)) (0.141.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.30.0->-r requirements.txt (line 8)) (0.52.4)
Requirement already satisfied: pydantic>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 9)) (2.13.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 10)) (2.1.3)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 11)) (1.6.1)
Requirement already satisfied: tqdm>=4.66.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 12)) (4.67.3)
Requirement already satisfied: python-multipart>=0.0.9 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 13)) (0.0.32)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (5.16.1)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (0.23.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (1.29.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (4.16.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from faiss-cpu>=1.8.0->-r requirements.txt (line 2)) (26.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.0->-r requirements.txt (line 3)) (3.32.5)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.0->-r requirements.txt (line 3)) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.0->-r requirements.txt (line 3)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.0->-r requirements.txt (line 3)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.0->-r requirements.txt (line 3)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2.0->-r requirements.txt (line 3)) (2025.12.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (0.27.2)
Requirement already satisfied: click<9.0.0,>=8.2.1 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (8.5.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from spacy>=3.7.0->-r requirements.txt (line 4)) (2.32.4)
Collecting pdfminer.six==20260107 (from pdfplumber>=0.11.0->-r requirements.txt (line 5))
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber>=0.11.0->-r requirements.txt (line 5))
  Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber>=0.11.0->-r requirements.txt (line 5))
  Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 895.0 kB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber>=0.11.0->-r requirements.txt (line 5)) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber>=0.11.0->-r requirements.txt (line 5)) (50.0.1)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from python-docx>=1.1.0->-r requirements.txt (line 6)) (6.1.2)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from fastapi>=0.111.0->-r requirements.txt (line 7)) (1.6.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi>=0.111.0->-r requirements.txt (line 7)) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi>=0.111.0->-r requirements.txt (line 7)) (0.0.5)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn>=0.30.0->uvicorn[standard]>=0.30.0->-r requirements.txt (line 8)) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.7.0->-r requirements.txt (line 9)) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.7.0->-r requirements.txt (line 9)) (2.46.5)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4.0->-r requirements.txt (line 11)) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4.0->-r requirements.txt (line 11)) (3.6.0)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.30.0->-r requirements.txt (line 8)) (0.8.0)
Requirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.30.0->-r requirements.txt (line 8)) (1.2.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.30.0->-r requirements.txt (line 8)) (6.0.3)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.30.0->-r requirements.txt (line 8)) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.30.0->-r requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.30.0->-r requirements.txt (line 8)) (15.0.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (0.28.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.4.0->-r requirements.txt (line 11)) (3.1.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.7.0->-r requirements.txt (line 4)) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.7.0->-r requirements.txt (line 4)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.7.0->-r requirements.txt (line 4)) (2026.7.22)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.13/dist-packages (from starlette>=0.46.0->fastapi>=0.111.0->-r requirements.txt (line 7)) (4.14.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.2.0->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from thinc<8.4.0,>=8.3.12->spacy>=3.7.0->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (2025.11.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.7.0->-r requirements.txt (line 4)) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.7.0->-r requirements.txt (line 4)) (13.9.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.7.0->-r requirements.txt (line 4)) (0.25.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.7.0->-r requirements.txt (line 4)) (8.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.2.0->-r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber>=0.11.0->-r requirements.txt (line 5)) (2.1.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=2.7.0->-r requirements.txt (line 1)) (1.0.9)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy>=3.7.0->-r requirements.txt (line 4)) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy>=3.7.0->-r requirements.txt (line 4)) (2.21.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy>=3.7.0->-r requirements.txt (line 4)) (2.4.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber>=0.11.0->-r requirements.txt (line 5)) (3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy>=3.7.0->-r requirements.txt (line 4)) (0.1.2)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 1.3 MB/s eta 0:00:00
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 4.6 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 3.0 MB/s eta 0:00:00
Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 1.3 MB/s eta 0:00:00
Installing collected packages: pypdfium2, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
Successfully installed Pillow-12.3.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdfium2-5.13.0

In [ ]:
!find . -maxdepth 3 -type f

./tests/test_pipeline.py
./README.md
./run_demo.py
./.git/config
./.git/logs/HEAD
./.git/hooks/push-to-checkout.sample
./.git/hooks/update.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/post-update.sample
./.git/hooks/commit-msg.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/pre-commit.sample
./.git/hooks/pre-push.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/sendemail-validate.sample
./.git/hooks/pre-receive.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/prepare-commit-msg.sample
./.git/HEAD
./.git/info/exclude
./.git/index
./.git/packed-refs
./.git/description
./data/jd.txt
./resume_screening_results.xlsx
./requirements.txt
./src/preprocessing.py
./src/__init__.py
./src/api.py
./src/similarity.py
./src/evaluation.py
./src/ingestion.py
./src/vector_store.py
./src/embedding.py
./src/pipeline.py
./.gitignore

In [ ]:
import sys
sys.path.append("/content/resume-sreening-and-skill-matching-2")

from src.ingestion import *
from src.preprocessing import *
from src.embedding import *
from src.similarity import *
from src.vector_store import *
from src.pipeline import *

print("✅ Project modules imported successfully!")

ImportError: cannot import name '_Ink' from 'PIL._typing' (/usr/local/lib/python3.13/dist-packages/PIL/_typing.py)

In [ ]:
!pip install --upgrade --force-reinstall "Pillow>=10.4.0"

Collecting Pillow>=10.4.0
  Using cached pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Using cached pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: pillow 12.3.0
    Uninstalling pillow-12.3.0:
      Successfully uninstalled pillow-12.3.0
Successfully installed Pillow-12.3.0

In [ ]:
%cd /content/resume-sreening-and-skill-matching-2

/content/resume-sreening-and-skill-matching-2

In [ ]:
import sys
sys.path.append("/content/resume-sreening-and-skill-matching-2")

from src.ingestion import *
from src.preprocessing import *
from src.embedding import *
from src.similarity import *
from src.vector_store import *
from src.pipeline import *

print("✅ Project modules imported successfully!")

✅ Project modules imported successfully!

In [ ]:
!sed -n '1,300p' run_demo.py

from __future__ import annotations

import argparse
import logging
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font, Alignment
from openpyxl.utils import get_column_letter

from src.pipeline import ResumeScreeningPipeline


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)


def get_decision(score: float) -> tuple[str, str]:

    if score >= 0.70:
        return "SELECTED", "Strong overall match with the job description."

    elif score >= 0.60:
        return "REVIEW", "Moderate match. Recruiter should review the candidate."

    else:
        return "REJECTED", "Low overall match with the job description."


def create_excel_report(ranked, output_file):

    workbook = Workbook()
    sheet = workbook.active

    sheet.title = "Screening Results"

    headers = [
        "Rank",
        "Resume File",
        "Overall Match Score",
        "Semantic Match",
        "Skill Match",
        "Decision",
        "Reason",
        "Matched Skills",
        "Missing Skills",
        "Experience",
        "Education"
    ]

    sheet.append(headers)

    # Header formatting
    for cell in sheet[1]:
        cell.font = Font(bold=True)
        cell.alignment = Alignment(
            horizontal="center",
            vertical="center"
        )

    # Add candidate data
    for rank, candidate in enumerate(ranked, start=1):

        decision, reason = get_decision(
            candidate.final_score
        )

        row = [
            rank,
            candidate.resume_id,
            round(candidate.final_score * 100, 2),
            round(candidate.semantic_score * 100, 2),
            round(candidate.skill_overlap_score * 100, 2),
            decision,
            reason,
            ", ".join(candidate.matched_skills)
            if candidate.matched_skills
            else "None",
            ", ".join(candidate.missing_skills)
            if candidate.missing_skills
            else "None",
            candidate.years_experience,
            ", ".join(candidate.education)
            if candidate.education
            else "None"
        ]

        sheet.append(row)

    # Format all cells
    for row in sheet.iter_rows():

        for cell in row:
            cell.alignment = Alignment(
                vertical="top",
                wrap_text=True
            )

    # Set column widths
    column_widths = {
        1: 8,
        2: 25,
        3: 20,
        4: 18,
        5: 15,
        6: 15,
        7: 45,
        8: 40,
        9: 40,
        10: 15,
        11: 20
    }

    for column, width in column_widths.items():
        sheet.column_dimensions[
            get_column_letter(column)
        ].width = width

    # Freeze header row
    sheet.freeze_panes = "A2"

    # Enable filtering
    sheet.auto_filter.ref = sheet.dimensions

    workbook.save(output_file)

    print(
        f"\nExcel report created successfully: {output_file}"
    )


def main():

    parser = argparse.ArgumentParser(
        description="Resume Matching and Candidate Selection System"
    )

    parser.add_argument(
        "--resumes_dir",
        required=True,
        help="Directory containing resume files (pdf/docx/txt)"
    )

    parser.add_argument(
        "--job_description",
        required=True,
        help="Path to a .txt file containing the job description"
    )

    parser.add_argument(
        "--top_k",
        type=int,
        default=10,
        help="Number of candidates to display"
    )

    parser.add_argument(
        "--min_similarity",
        type=float,
        default=0.0
    )

    parser.add_argument(
        "--min_years_experience",
        type=float,
        default=None
    )

    parser.add_argument(
        "--min_education",
        type=str,
        default=None,
        choices=[
            None,
            "High School",
            "Associate",
            "Bachelors",
            "Masters",
            "PhD"
        ]
    )

    parser.add_argument(
        "--save_index_to",
        type=str,
        default=None,
        help="Optional directory to save the FAISS index"
    )

    args = parser.parse_args()

    jd_text = Path(
        args.job_description
    ).read_text(
        encoding="utf-8",
        errors="ignore"
    )

    pipeline = ResumeScreeningPipeline(
        batch_size=128
    )

    print("\n" + "=" * 70)
    print("          RESUME MATCHING & SELECTION SYSTEM")
    print("=" * 70)

    print(
        f"\nIndexing resumes from: {args.resumes_dir}"
    )

    index_report = pipeline.index_directory(
        args.resumes_dir,
        batch_size=150
    )

    print(
        f"Indexed: {index_report['indexed']}  "
        f"Failed: {len(index_report['failed'])}"
    )

    print(
        f"Performance: {index_report['performance']}"
    )

    if index_report["failed"]:

        print("\nFailed resumes:")

        for resume_id in index_report["failed"]:
            print(f"  - {resume_id}")

    if args.save_index_to:

        pipeline.save_index(
            args.save_index_to
        )

        print(
            f"\nIndex saved to: {args.save_index_to}"
        )

    ranked = pipeline.match(
        job_description_text=jd_text,
        top_k=args.top_k,
        min_similarity=args.min_similarity,
        min_years_experience=args.min_years_experience,
        min_education=args.min_education,
    )

    # ---------------- TERMINAL RESULTS ----------------

    print("\n" + "=" * 70)
    print("                    SCREENING RESULTS")
    print("=" * 70)

    print(
        f"\nCandidates analyzed: {index_report['indexed']}"
    )

    print(
        f"Candidates displayed: {len(ranked)}"
    )

    print("\n" + "-" * 70)

    print(
        f"{'Rank':<6}"
        f"{'Candidate':<20}"
        f"{'Score':<12}"
        f"{'Decision'}"
    )

    print("-" * 70)

    for i, candidate in enumerate(
        ranked,
        start=1
    ):

        decision, reason = get_decision(
            candidate.final_score
        )

        score_percentage = (
            candidate.final_score * 100
        )

        print(
            f"{i:<6}"
            f"{candidate.resume_id:<20}"
            f"{score_percentage:>6.1f}%     "
            f"{decision}"
        )

    print("-" * 70)

    # ---------------- EXCEL REPORT ----------------

In [ ]:
!find data -maxdepth 2 -type f | head -30

data/jd.txt

In [ ]:
!cat data/jd.txt

We are seeking an AI Engineer to design, develop, and deploy machine learning and generative AI solutions. The ideal candidate will have strong experience in Python, machine learning, deep learning, NLP, LLMs, and MLOps, with the ability to build scalable production systems. Responsibilities
Develop and deploy machine learning and AI models.
Build data pipelines and model workflows.
Support model training, testing, and evaluation.
Integrate AI solutions into production applications.
Monitor model performance and improve accuracy and reliability.
Work with cross-functional teams to deliver AI features.
Requirements
knows AI, machine learning, or data science.
Strong programming skills in Python.
Experience with TensorFlow, PyTorch, Scikit-learn, or Hugging Face.
Knowledge of NLP, LLMs, RAG, or prompt engineering.
Experience with Docker, Kubernetes, AWS, Azure, or GCP.
Understanding of model deployment, monitoring, and lifecycle management.
Preferred Skills
Experience with FastAPI, SQL, MLflow, Airflow, or CI/CD.
Familiarity with computer vision or recommendation systems.
Strong communication and problem-solving skills.

In [ ]:
!find data -maxdepth 2 -type f | head -30

data/jd.txt

In [ ]:
!find /content -type f \( -iname "*.pdf" -o -iname "*.docx" -o -iname "*.txt" \) | head -30

/content/resume-sreening-and-skill-matching-2/data/jd.txt
/content/resume-sreening-and-skill-matching-2/resume-sreening-and-skill-matching-2/data/jd.txt
/content/resume-sreening-and-skill-matching-2/resume-sreening-and-skill-matching-2/requirements.txt
/content/resume-sreening-and-skill-matching-2/requirements.txt

In [ ]:
!cat data/jd.txt

We are seeking an AI Engineer to design, develop, and deploy machine learning and generative AI solutions. The ideal candidate will have strong experience in Python, machine learning, deep learning, NLP, LLMs, and MLOps, with the ability to build scalable production systems. Responsibilities
Develop and deploy machine learning and AI models.
Build data pipelines and model workflows.
Support model training, testing, and evaluation.
Integrate AI solutions into production applications.
Monitor model performance and improve accuracy and reliability.
Work with cross-functional teams to deliver AI features.
Requirements
knows AI, machine learning, or data science.
Strong programming skills in Python.
Experience with TensorFlow, PyTorch, Scikit-learn, or Hugging Face.
Knowledge of NLP, LLMs, RAG, or prompt engineering.
Experience with Docker, Kubernetes, AWS, Azure, or GCP.
Understanding of model deployment, monitoring, and lifecycle management.
Preferred Skills
Experience with FastAPI, SQL, MLflow, Airflow, or CI/CD.
Familiarity with computer vision or recommendation systems.
Strong communication and problem-solving skills.

In [ ]:
!find /content -type f \( -iname "*.pdf" -o -iname "*.docx" -o -iname "*.txt" \) | head -30

/content/resume-sreening-and-skill-matching-2/data/jd.txt
/content/resume-sreening-and-skill-matching-2/resume-sreening-and-skill-matching-2/data/jd.txt
/content/resume-sreening-and-skill-matching-2/resume-sreening-and-skill-matching-2/requirements.txt
/content/resume-sreening-and-skill-matching-2/requirements.txt

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving task-resume-matching-with-job-descriptions.ipynb to task-resume-matching-with-job-descriptions.ipynb

In [ ]:
!find /content -type f \( -iname "*.pdf" -o -iname "*.docx" -o -iname "*.txt" \) | head -50

/content/resume-sreening-and-skill-matching-2/data/jd.txt
/content/resume-sreening-and-skill-matching-2/resume-sreening-and-skill-matching-2/data/jd.txt
/content/resume-sreening-and-skill-matching-2/resume-sreening-and-skill-matching-2/requirements.txt
/content/resume-sreening-and-skill-matching-2/requirements.txt

In [ ]:
from google.colab import files

uploaded = files.upload()

print("Uploaded files:")
for filename in uploaded.keys():
    print(filename)

Saving ACCOUNTANT_10554236.pdf to ACCOUNTANT_10554236.pdf
Saving ACCOUNTANT_10674770.pdf to ACCOUNTANT_10674770.pdf
Saving ACCOUNTANT_11163645.pdf to ACCOUNTANT_11163645.pdf
Saving adhhul.pdf to adhhul.pdf
Saving ADVOCATE_10186968.pdf to ADVOCATE_10186968.pdf
Saving ADVOCATE_10344379.pdf to ADVOCATE_10344379.pdf
Saving ADVOCATE_10659182.pdf to ADVOCATE_10659182.pdf
Saving AGRICULTURE_10953078.pdf to AGRICULTURE_10953078.pdf
Saving AGRICULTURE_11197262.pdf to AGRICULTURE_11197262.pdf
Saving althaf.docx to althaf.docx
Saving AlthafMohammadBabu_Resume.docx to AlthafMohammadBabu_Resume.docx
Saving APPAREL_10182582.pdf to APPAREL_10182582.pdf
Saving APPAREL_10562768.pdf to APPAREL_10562768.pdf
Saving ARTS_10830646.pdf to ARTS_10830646.pdf
Saving ARTS_11187796.pdf to ARTS_11187796.pdf
Saving AUTOMOBILE_11152490.pdf to AUTOMOBILE_11152490.pdf
Saving AUTOMOBILE_11257723.pdf to AUTOMOBILE_11257723.pdf
Saving AVIATION_10176815.pdf to AVIATION_10176815.pdf
Saving AVIATION_10189110.pdf to AVIATION_10189110.pdf
Saving BANKING_10329506.pdf to BANKING_10329506.pdf
Saving BANKING_10909673.pdf to BANKING_10909673.pdf
Saving BPO_11183737.pdf to BPO_11183737.pdf
Saving BPO_13964744.pdf to BPO_13964744.pdf
Saving BUSINESS-DEVELOPMENT_10228751.pdf to BUSINESS-DEVELOPMENT_10228751.pdf
Saving BUSINESS-DEVELOPMENT_10235211.pdf to BUSINESS-DEVELOPMENT_10235211.pdf
Saving CHEF_10001727.pdf to CHEF_10001727.pdf
Saving CHEF_10276858.pdf to CHEF_10276858.pdf
Saving CONSTRUCTION_10041713.pdf to CONSTRUCTION_10041713.pdf
Saving CONSTRUCTION_10100240.pdf to CONSTRUCTION_10100240.pdf
Saving CONSULTANT_10332998.pdf to CONSULTANT_10332998.pdf
Saving CONSULTANT_10984392.pdf to CONSULTANT_10984392.pdf
Saving DESIGNER_10466583.pdf to DESIGNER_10466583.pdf
Saving DESIGNER_10748989.pdf to DESIGNER_10748989.pdf
Saving DIGITAL-MEDIA_10005171.pdf to DIGITAL-MEDIA_10005171.pdf
Saving DIGITAL-MEDIA_10515955.pdf to DIGITAL-MEDIA_10515955.pdf
Saving ENGINEERING_10030015.pdf to ENGINEERING_10030015.pdf
Saving ENGINEERING_10219099.pdf to ENGINEERING_10219099.pdf
Saving FINANCE_10549585.pdf to FINANCE_10549585.pdf
Saving FINANCE_11441764.pdf to FINANCE_11441764.pdf
Saving FITNESS_10235429.pdf to FITNESS_10235429.pdf
Saving FITNESS_10268614.pdf to FITNESS_10268614.pdf
Saving HEALTHCARE_10062724.pdf to HEALTHCARE_10062724.pdf
Saving HEALTHCARE_10076271.pdf to HEALTHCARE_10076271.pdf
Saving HR_10399912.pdf to HR_10399912.pdf
Saving HR_10694288.pdf to HR_10694288.pdf
Saving INFORMATION-TECHNOLOGY_10089434.pdf to INFORMATION-TECHNOLOGY_10089434.pdf
Saving INFORMATION-TECHNOLOGY_10247517.pdf to INFORMATION-TECHNOLOGY_10247517.pdf
Saving PUBLIC-RELATIONS_10070224.pdf to PUBLIC-RELATIONS_10070224.pdf
Saving PUBLIC-RELATIONS_10554045.pdf to PUBLIC-RELATIONS_10554045.pdf
Saving rahul.pdf to rahul.pdf
Saving ramesh.pdf to ramesh.pdf
Saving SALES_10138632.pdf to SALES_10138632.pdf
Saving SALES_10464113.pdf to SALES_10464113.pdf
Saving sam.pdf to sam.pdf
Saving samantha.pdf to samantha.pdf
Saving shifa.pdf to shifa.pdf
Saving sinu.pdf to sinu.pdf
Saving susan.pdf to susan.pdf
Saving TEACHER_10504237.pdf to TEACHER_10504237.pdf
Saving TEACHER_10527994.pdf to TEACHER_10527994.pdf
Saving wikki.pdf to wikki.pdf
Uploaded files:
ACCOUNTANT_10554236.pdf
ACCOUNTANT_10674770.pdf
ACCOUNTANT_11163645.pdf
adhhul.pdf
ADVOCATE_10186968.pdf
ADVOCATE_10344379.pdf
ADVOCATE_10659182.pdf
AGRICULTURE_10953078.pdf
AGRICULTURE_11197262.pdf
althaf.docx
AlthafMohammadBabu_Resume.docx
APPAREL_10182582.pdf
APPAREL_10562768.pdf
ARTS_10830646.pdf
ARTS_11187796.pdf
AUTOMOBILE_11152490.pdf
AUTOMOBILE_11257723.pdf
AVIATION_10176815.pdf
AVIATION_10189110.pdf
BANKING_10329506.pdf
BANKING_10909673.pdf
BPO_11183737.pdf
BPO_13964744.pdf
BUSINESS-DEVELOPMENT_10228751.pdf
BUSINESS-DEVELOPMENT_10235211.pdf
CHEF_10001727.pdf
CHEF_10276858.pdf
CONSTRUCTION_10041713.pdf
CONSTRUCTION_10100240.pdf
CONSULTANT_10332998.pdf
CONSULTANT_10984392.pdf
DESIGNER_10466583.pdf
DESIGNER_10748989.pdf
DIGITAL-MEDIA_10005171.pdf
DIGITAL-MEDIA_10515955.pdf
ENGINEERING_10030015.pdf
ENGINEERING_10219099.pdf
FINANCE_10549585.pdf
FINANCE_11441764.pdf
FITNESS_10235429.pdf
FITNESS_10268614.pdf
HEALTHCARE_10062724.pdf
HEALTHCARE_10076271.pdf
HR_10399912.pdf
HR_10694288.pdf
INFORMATION-TECHNOLOGY_10089434.pdf
INFORMATION-TECHNOLOGY_10247517.pdf
PUBLIC-RELATIONS_10070224.pdf
PUBLIC-RELATIONS_10554045.pdf
rahul.pdf
ramesh.pdf
SALES_10138632.pdf
SALES_10464113.pdf
sam.pdf
samantha.pdf
shifa.pdf
sinu.pdf
susan.pdf
TEACHER_10504237.pdf
TEACHER_10527994.pdf
wikki.pdf

In [ ]:
!ls -lh /content

total 8.0K
drwxr-xr-x 7 root root 4.0K Sep 18 14:18 resume-sreening-and-skill-matching-2
drwxr-xr-x 1 root root 4.0K Sep 16 13:26 sample_data

In [ ]:
from google.colab import files

uploaded = files.upload()

print("\nUploaded:")
for filename in uploaded:
    print("✅", filename)

Saving ACCOUNTANT_10554236.pdf to ACCOUNTANT_10554236 (1).pdf
Saving ACCOUNTANT_10674770.pdf to ACCOUNTANT_10674770 (1).pdf
Saving ACCOUNTANT_11163645.pdf to ACCOUNTANT_11163645 (1).pdf
Saving adhhul.pdf to adhhul (1).pdf
Saving ADVOCATE_10186968.pdf to ADVOCATE_10186968 (1).pdf
Saving ADVOCATE_10344379.pdf to ADVOCATE_10344379 (1).pdf
Saving ADVOCATE_10659182.pdf to ADVOCATE_10659182 (1).pdf
Saving AGRICULTURE_10953078.pdf to AGRICULTURE_10953078 (1).pdf
Saving AGRICULTURE_11197262.pdf to AGRICULTURE_11197262 (1).pdf
Saving althaf.docx to althaf (1).docx
Saving AlthafMohammadBabu_Resume.docx to AlthafMohammadBabu_Resume (1).docx
Saving APPAREL_10182582.pdf to APPAREL_10182582 (1).pdf
Saving APPAREL_10562768.pdf to APPAREL_10562768 (1).pdf
Saving ARTS_10830646.pdf to ARTS_10830646 (1).pdf
Saving ARTS_11187796.pdf to ARTS_11187796 (1).pdf
Saving AUTOMOBILE_11152490.pdf to AUTOMOBILE_11152490 (1).pdf
Saving AUTOMOBILE_11257723.pdf to AUTOMOBILE_11257723 (1).pdf
Saving AVIATION_10176815.pdf to AVIATION_10176815 (1).pdf
Saving AVIATION_10189110.pdf to AVIATION_10189110 (1).pdf
Saving BANKING_10329506.pdf to BANKING_10329506 (1).pdf
Saving BANKING_10909673.pdf to BANKING_10909673 (1).pdf
Saving BPO_11183737.pdf to BPO_11183737 (1).pdf
Saving BPO_13964744.pdf to BPO_13964744 (1).pdf
Saving BUSINESS-DEVELOPMENT_10228751.pdf to BUSINESS-DEVELOPMENT_10228751 (1).pdf
Saving BUSINESS-DEVELOPMENT_10235211.pdf to BUSINESS-DEVELOPMENT_10235211 (1).pdf
Saving CHEF_10001727.pdf to CHEF_10001727 (1).pdf
Saving CHEF_10276858.pdf to CHEF_10276858 (1).pdf
Saving CONSTRUCTION_10041713.pdf to CONSTRUCTION_10041713 (1).pdf
Saving CONSTRUCTION_10100240.pdf to CONSTRUCTION_10100240 (1).pdf
Saving CONSULTANT_10332998.pdf to CONSULTANT_10332998 (1).pdf
Saving CONSULTANT_10984392.pdf to CONSULTANT_10984392 (1).pdf
Saving DESIGNER_10466583.pdf to DESIGNER_10466583 (1).pdf
Saving DESIGNER_10748989.pdf to DESIGNER_10748989 (1).pdf
Saving DIGITAL-MEDIA_10005171.pdf to DIGITAL-MEDIA_10005171 (1).pdf
Saving DIGITAL-MEDIA_10515955.pdf to DIGITAL-MEDIA_10515955 (1).pdf
Saving ENGINEERING_10030015.pdf to ENGINEERING_10030015 (1).pdf
Saving ENGINEERING_10219099.pdf to ENGINEERING_10219099 (1).pdf
Saving FINANCE_10549585.pdf to FINANCE_10549585 (1).pdf
Saving FINANCE_11441764.pdf to FINANCE_11441764 (1).pdf
Saving FITNESS_10235429.pdf to FITNESS_10235429 (1).pdf
Saving FITNESS_10268614.pdf to FITNESS_10268614 (1).pdf
Saving HEALTHCARE_10062724.pdf to HEALTHCARE_10062724 (1).pdf
Saving HEALTHCARE_10076271.pdf to HEALTHCARE_10076271 (1).pdf
Saving HR_10399912.pdf to HR_10399912 (1).pdf
Saving HR_10694288.pdf to HR_10694288 (1).pdf
Saving INFORMATION-TECHNOLOGY_10089434.pdf to INFORMATION-TECHNOLOGY_10089434 (1).pdf
Saving INFORMATION-TECHNOLOGY_10247517.pdf to INFORMATION-TECHNOLOGY_10247517 (1).pdf
Saving PUBLIC-RELATIONS_10070224.pdf to PUBLIC-RELATIONS_10070224 (1).pdf
Saving PUBLIC-RELATIONS_10554045.pdf to PUBLIC-RELATIONS_10554045 (1).pdf
Saving rahul.pdf to rahul (1).pdf
Saving ramesh.pdf to ramesh (1).pdf
Saving SALES_10138632.pdf to SALES_10138632 (1).pdf
Saving SALES_10464113.pdf to SALES_10464113 (1).pdf
Saving sam.pdf to sam (1).pdf
Saving samantha.pdf to samantha (1).pdf
Saving shifa.pdf to shifa (1).pdf
Saving sinu.pdf to sinu (1).pdf
Saving susan.pdf to susan (1).pdf
Saving TEACHER_10504237.pdf to TEACHER_10504237 (1).pdf
Saving TEACHER_10527994.pdf to TEACHER_10527994 (1).pdf
Saving wikki.pdf to wikki (1).pdf

Uploaded:
✅ ACCOUNTANT_10554236 (1).pdf
✅ ACCOUNTANT_10674770 (1).pdf
✅ ACCOUNTANT_11163645 (1).pdf
✅ adhhul (1).pdf
✅ ADVOCATE_10186968 (1).pdf
✅ ADVOCATE_10344379 (1).pdf
✅ ADVOCATE_10659182 (1).pdf
✅ AGRICULTURE_10953078 (1).pdf
✅ AGRICULTURE_11197262 (1).pdf
✅ althaf (1).docx
✅ AlthafMohammadBabu_Resume (1).docx
✅ APPAREL_10182582 (1).pdf
✅ APPAREL_10562768 (1).pdf
✅ ARTS_10830646 (1).pdf
✅ ARTS_11187796 (1).pdf
✅ AUTOMOBILE_11152490 (1).pdf
✅ AUTOMOBILE_11257723 (1).pdf
✅ AVIATION_10176815 (1).pdf
✅ AVIATION_10189110 (1).pdf
✅ BANKING_10329506 (1).pdf
✅ BANKING_10909673 (1).pdf
✅ BPO_11183737 (1).pdf
✅ BPO_13964744 (1).pdf
✅ BUSINESS-DEVELOPMENT_10228751 (1).pdf
✅ BUSINESS-DEVELOPMENT_10235211 (1).pdf
✅ CHEF_10001727 (1).pdf
✅ CHEF_10276858 (1).pdf
✅ CONSTRUCTION_10041713 (1).pdf
✅ CONSTRUCTION_10100240 (1).pdf
✅ CONSULTANT_10332998 (1).pdf
✅ CONSULTANT_10984392 (1).pdf
✅ DESIGNER_10466583 (1).pdf
✅ DESIGNER_10748989 (1).pdf
✅ DIGITAL-MEDIA_10005171 (1).pdf
✅ DIGITAL-MEDIA_10515955 (1).pdf
✅ ENGINEERING_10030015 (1).pdf
✅ ENGINEERING_10219099 (1).pdf
✅ FINANCE_10549585 (1).pdf
✅ FINANCE_11441764 (1).pdf
✅ FITNESS_10235429 (1).pdf
✅ FITNESS_10268614 (1).pdf
✅ HEALTHCARE_10062724 (1).pdf
✅ HEALTHCARE_10076271 (1).pdf
✅ HR_10399912 (1).pdf
✅ HR_10694288 (1).pdf
✅ INFORMATION-TECHNOLOGY_10089434 (1).pdf
✅ INFORMATION-TECHNOLOGY_10247517 (1).pdf
✅ PUBLIC-RELATIONS_10070224 (1).pdf
✅ PUBLIC-RELATIONS_10554045 (1).pdf
✅ rahul (1).pdf
✅ ramesh (1).pdf
✅ SALES_10138632 (1).pdf
✅ SALES_10464113 (1).pdf
✅ sam (1).pdf
✅ samantha (1).pdf
✅ shifa (1).pdf
✅ sinu (1).pdf
✅ susan (1).pdf
✅ TEACHER_10504237 (1).pdf
✅ TEACHER_10527994 (1).pdf
✅ wikki (1).pdf

In [ ]:
!ls -lh /content

total 16K
drwxr-xr-x 7 root root  12K Sep 18 14:23 resume-sreening-and-skill-matching-2
drwxr-xr-x 1 root root 4.0K Sep 16 13:26 sample_data

In [ ]:
!find /content/resume-sreening-and-skill-matching-2 -type f | grep -Ei '\.(pdf|docx|zip)$' | head -50

/content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10515955 (1).pdf
/content/resume-sreening-and-skill-matching-2/APPAREL_10562768.pdf
/content/resume-sreening-and-skill-matching-2/FITNESS_10235429 (1).pdf
/content/resume-sreening-and-skill-matching-2/AGRICULTURE_10953078.pdf
/content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10674770.pdf
/content/resume-sreening-and-skill-matching-2/INFORMATION-TECHNOLOGY_10247517.pdf
/content/resume-sreening-and-skill-matching-2/sam (1).pdf
/content/resume-sreening-and-skill-matching-2/TEACHER_10504237 (1).pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10344379.pdf
/content/resume-sreening-and-skill-matching-2/HEALTHCARE_10062724 (1).pdf
/content/resume-sreening-and-skill-matching-2/FINANCE_10549585 (1).pdf
/content/resume-sreening-and-skill-matching-2/sinu (1).pdf
/content/resume-sreening-and-skill-matching-2/ENGINEERING_10219099.pdf
/content/resume-sreening-and-skill-matching-2/ENGINEERING_10030015.pdf
/content/resume-sreening-and-skill-matching-2/sinu.pdf
/content/resume-sreening-and-skill-matching-2/BPO_11183737.pdf
/content/resume-sreening-and-skill-matching-2/AGRICULTURE_11197262 (1).pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10332998.pdf
/content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10041713 (1).pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10659182 (1).pdf
/content/resume-sreening-and-skill-matching-2/HR_10694288 (1).pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10332998 (1).pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10984392 (1).pdf
/content/resume-sreening-and-skill-matching-2/BANKING_10329506 (1).pdf
/content/resume-sreening-and-skill-matching-2/althaf.docx
/content/resume-sreening-and-skill-matching-2/HEALTHCARE_10076271.pdf
/content/resume-sreening-and-skill-matching-2/ramesh (1).pdf
/content/resume-sreening-and-skill-matching-2/HR_10694288.pdf
/content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10554236 (1).pdf
/content/resume-sreening-and-skill-matching-2/samantha (1).pdf
/content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10041713.pdf
/content/resume-sreening-and-skill-matching-2/AGRICULTURE_11197262.pdf
/content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10228751 (1).pdf
/content/resume-sreening-and-skill-matching-2/susan.pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10984392.pdf
/content/resume-sreening-and-skill-matching-2/ARTS_10830646.pdf
/content/resume-sreening-and-skill-matching-2/HR_10399912.pdf
/content/resume-sreening-and-skill-matching-2/TEACHER_10504237.pdf
/content/resume-sreening-and-skill-matching-2/APPAREL_10562768 (1).pdf
/content/resume-sreening-and-skill-matching-2/FITNESS_10235429.pdf
/content/resume-sreening-and-skill-matching-2/SALES_10138632 (1).pdf
/content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10070224 (1).pdf
/content/resume-sreening-and-skill-matching-2/SALES_10138632.pdf
/content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10515955.pdf
/content/resume-sreening-and-skill-matching-2/samantha.pdf
/content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10235211.pdf
/content/resume-sreening-and-skill-matching-2/rahul.pdf
/content/resume-sreening-and-skill-matching-2/HR_10399912 (1).pdf
/content/resume-sreening-and-skill-matching-2/SALES_10464113 (1).pdf
/content/resume-sreening-and-skill-matching-2/TEACHER_10527994 (1).pdf

In [ ]:
!find /content -type f -mmin -10 -ls

  1703952      4 -rw-------   1 root     root            5 Jan  1  2040 /content/.config/gce
   272602     28 -rw-r--r--   1 root     root        24675 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10515955\ (1).pdf
   272519     24 -rw-r--r--   1 root     root        24540 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/APPAREL_10562768.pdf
   272607     24 -rw-r--r--   1 root     root        22675 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/FITNESS_10235429\ (1).pdf
   272514     24 -rw-r--r--   1 root     root        23418 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/AGRICULTURE_10953078.pdf
   272508     28 -rw-r--r--   1 root     root        25155 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10674770.pdf
   272553     28 -rw-r--r--   1 root     root        25304 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/INFORMATION-TECHNOLOGY_10247517.pdf
   272621     24 -rw-r--r--   1 root     root        20770 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/sam\ (1).pdf
   272626     28 -rw-r--r--   1 root     root        24655 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/TEACHER_10504237\ (1).pdf
   272512     24 -rw-r--r--   1 root     root        21027 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ADVOCATE_10344379.pdf
   272609     32 -rw-r--r--   1 root     root        31779 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/HEALTHCARE_10062724\ (1).pdf
   272605     40 -rw-r--r--   1 root     root        40023 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/FINANCE_10549585\ (1).pdf
   272624     20 -rw-r--r--   1 root     root        20284 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/sinu\ (1).pdf
   272543     28 -rw-r--r--   1 root     root        25581 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ENGINEERING_10219099.pdf
   272542     20 -rw-r--r--   1 root     root        17940 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ENGINEERING_10030015.pdf
   272563     20 -rw-r--r--   1 root     root        20284 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/sinu.pdf
   272528     28 -rw-r--r--   1 root     root        27910 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/BPO_11183737.pdf
   272576     24 -rw-r--r--   1 root     root        21771 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/AGRICULTURE_11197262\ (1).pdf
   272536     32 -rw-r--r--   1 root     root        28704 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/CONSULTANT_10332998.pdf
   272595     24 -rw-r--r--   1 root     root        23415 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10041713\ (1).pdf
   272574     24 -rw-r--r--   1 root     root        21691 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ADVOCATE_10659182\ (1).pdf
   272612     24 -rw-r--r--   1 root     root        21641 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/HR_10694288\ (1).pdf
   272597     32 -rw-r--r--   1 root     root        28704 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/CONSULTANT_10332998\ (1).pdf
   272598     24 -rw-r--r--   1 root     root        24138 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/CONSULTANT_10984392\ (1).pdf
   272587     20 -rw-r--r--   1 root     root        20169 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/BANKING_10329506\ (1).pdf
   272516    168 -rw-r--r--   1 root     root       170966 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/althaf.docx
   272549     24 -rw-r--r--   1 root     root        24208 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/HEALTHCARE_10076271.pdf
   272618     28 -rw-r--r--   1 root     root        28103 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ramesh\ (1).pdf
   272551     24 -rw-r--r--   1 root     root        21641 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/HR_10694288.pdf
   272568     48 -rw-r--r--   1 root     root        48278 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10554236\ (1).pdf
   272622     28 -rw-r--r--   1 root     root        28128 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/samantha\ (1).pdf
   272534     24 -rw-r--r--   1 root     root        23415 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10041713.pdf
   272515     24 -rw-r--r--   1 root     root        21771 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/AGRICULTURE_11197262.pdf
   272591     20 -rw-r--r--   1 root     root        20368 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10228751\ (1).pdf
   272564    100 -rw-r--r--   1 root     root       101699 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/susan.pdf
   272537     24 -rw-r--r--   1 root     root        24138 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/CONSULTANT_10984392.pdf
   272520     28 -rw-r--r--   1 root     root        28416 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ARTS_10830646.pdf
   272550     24 -rw-r--r--   1 root     root        23183 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/HR_10399912.pdf
   272565     28 -rw-r--r--   1 root     root        24655 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/TEACHER_10504237.pdf
   272580     24 -rw-r--r--   1 root     root        24540 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/APPAREL_10562768\ (1).pdf
   272546     24 -rw-r--r--   1 root     root        22675 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/FITNESS_10235429.pdf
   272619     24 -rw-r--r--   1 root     root        21636 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/SALES_10138632\ (1).pdf
   272615     36 -rw-r--r--   1 root     root        32816 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10070224\ (1).pdf
   272558     24 -rw-r--r--   1 root     root        21636 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/SALES_10138632.pdf
   272541     28 -rw-r--r--   1 root     root        24675 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10515955.pdf
   272561     28 -rw-r--r--   1 root     root        28128 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/samantha.pdf
   272531     28 -rw-r--r--   1 root     root        25304 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10235211.pdf
   272556     28 -rw-r--r--   1 root     root        28154 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/rahul.pdf
   272611     24 -rw-r--r--   1 root     root        23183 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/HR_10399912\ (1).pdf
   272620     24 -rw-r--r--   1 root     root        22718 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/SALES_10464113\ (1).pdf
   272627     16 -rw-r--r--   1 root     root        16002 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/TEACHER_10527994\ (1).pdf
   272596     28 -rw-r--r--   1 root     root        24640 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10100240\ (1).pdf
   272525     28 -rw-r--r--   1 root     root        25976 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/AVIATION_10189110.pdf
   272522     36 -rw-r--r--   1 root     root        33949 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/AUTOMOBILE_11152490.pdf
   272524     24 -rw-r--r--   1 root     root        22232 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/AVIATION_10176815.pdf
   272538     16 -rw-r--r--   1 root     root        15389 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/DESIGNER_10466583.pdf
   272540     44 -rw-r--r--   1 root     root        42231 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10005171.pdf
   272573     24 -rw-r--r--   1 root     root        21027 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ADVOCATE_10344379\ (1).pdf
   272628     96 -rw-r--r--   1 root     root        97670 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/wikki\ (1).pdf
   272554     36 -rw-r--r--   1 root     root        32816 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10070224.pdf
   272517    168 -rw-r--r--   1 root     root       170966 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/AlthafMohammadBabu_Resume.docx
   272572     24 -rw-r--r--   1 root     root        20960 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ADVOCATE_10186968\ (1).pdf
   272588     24 -rw-r--r--   1 root     root        22606 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/BANKING_10909673\ (1).pdf
   272521     20 -rw-r--r--   1 root     root        17801 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ARTS_11187796.pdf
   272577    168 -rw-r--r--   1 root     root       170966 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/althaf\ (1).docx
   272601     44 -rw-r--r--   1 root     root        42231 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10005171\ (1).pdf
   272578    168 -rw-r--r--   1 root     root       170966 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/AlthafMohammadBabu_Resume\ (1).docx
   272623     20 -rw-r--r--   1 root     root        20082 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/shifa\ (1).pdf
   272557     28 -rw-r--r--   1 root     root        28103 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ramesh.pdf
   272570     24 -rw-r--r--   1 root     root        22333 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ACCOUNTANT_11163645\ (1).pdf
   272616     24 -rw-r--r--   1 root     root        24079 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10554045\ (1).pdf
   272545     24 -rw-r--r--   1 root     root        24498 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/FINANCE_11441764.pdf
   272547     24 -rw-r--r--   1 root     root        23841 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/FITNESS_10268614.pdf
   272535     28 -rw-r--r--   1 root     root        24640 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10100240.pdf
   272562     20 -rw-r--r--   1 root     root        20082 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/shifa.pdf
   272510     28 -rw-r--r--   1 root     root        28117 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/adhhul.pdf
   272613     28 -rw-r--r--   1 root     root        27103 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/INFORMATION-TECHNOLOGY_10089434\ (1).pdf
   272511     24 -rw-r--r--   1 root     root        20960 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ADVOCATE_10186968.pdf
   272594     36 -rw-r--r--   1 root     root        35716 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/CHEF_10276858\ (1).pdf
   272585     24 -rw-r--r--   1 root     root        22232 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/AVIATION_10176815\ (1).pdf
   272571     28 -rw-r--r--   1 root     root        28117 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/adhhul\ (1).pdf
   272575     24 -rw-r--r--   1 root     root        23418 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/AGRICULTURE_10953078\ (1).pdf
   272555     24 -rw-r--r--   1 root     root        24079 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10554045.pdf
   272625    100 -rw-r--r--   1 root     root       101699 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/susan\ (1).pdf
   272566     16 -rw-r--r--   1 root     root        16002 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/TEACHER_10527994.pdf
   272544     40 -rw-r--r--   1 root     root        40023 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/FINANCE_10549585.pdf
   272507     48 -rw-r--r--   1 root     root        48278 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10554236.pdf
   272593     24 -rw-r--r--   1 root     root        23322 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/CHEF_10001727\ (1).pdf
   272583     36 -rw-r--r--   1 root     root        33949 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/AUTOMOBILE_11152490\ (1).pdf
   272526     20 -rw-r--r--   1 root     root        20169 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/BANKING_10329506.pdf
   272518     20 -rw-r--r--   1 root     root        16859 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/APPAREL_10182582.pdf
   272600     24 -rw-r--r--   1 root     root        24132 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/DESIGNER_10748989\ (1).pdf
   272532     24 -rw-r--r--   1 root     root        23322 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/CHEF_10001727.pdf
   272617     28 -rw-r--r--   1 root     root        28154 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/rahul\ (1).pdf
   272529     28 -rw-r--r--   1 root     root        25643 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/BPO_13964744.pdf
   272608     24 -rw-r--r--   1 root     root        23841 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/FITNESS_10268614\ (1).pdf
   272610     24 -rw-r--r--   1 root     root        24208 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/HEALTHCARE_10076271\ (1).pdf
   272548     32 -rw-r--r--   1 root     root        31779 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/HEALTHCARE_10062724.pdf
   272569     28 -rw-r--r--   1 root     root        25155 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10674770\ (1).pdf
   272559     24 -rw-r--r--   1 root     root        22718 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/SALES_10464113.pdf
   272509     24 -rw-r--r--   1 root     root        22333 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ACCOUNTANT_11163645.pdf
   272552     28 -rw-r--r--   1 root     root        27103 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/INFORMATION-TECHNOLOGY_10089434.pdf
   272614     28 -rw-r--r--   1 root     root        25304 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/INFORMATION-TECHNOLOGY_10247517\ (1).pdf
   272590     28 -rw-r--r--   1 root     root        25643 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/BPO_13964744\ (1).pdf
   272592     28 -rw-r--r--   1 root     root        25304 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10235211\ (1).pdf
   272560     24 -rw-r--r--   1 root     root        20770 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/sam.pdf
   272586     28 -rw-r--r--   1 root     root        25976 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/AVIATION_10189110\ (1).pdf
   272523     20 -rw-r--r--   1 root     root        18606 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/AUTOMOBILE_11257723.pdf
   272584     20 -rw-r--r--   1 root     root        18606 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/AUTOMOBILE_11257723\ (1).pdf
   272581     28 -rw-r--r--   1 root     root        28416 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ARTS_10830646\ (1).pdf
   272533     36 -rw-r--r--   1 root     root        35716 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/CHEF_10276858.pdf
   272606     24 -rw-r--r--   1 root     root        24498 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/FINANCE_11441764\ (1).pdf
   272567     96 -rw-r--r--   1 root     root        97670 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/wikki.pdf
   272579     20 -rw-r--r--   1 root     root        16859 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/APPAREL_10182582\ (1).pdf
   272599     16 -rw-r--r--   1 root     root        15389 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/DESIGNER_10466583\ (1).pdf
   272603     20 -rw-r--r--   1 root     root        17940 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ENGINEERING_10030015\ (1).pdf
   272539     24 -rw-r--r--   1 root     root        24132 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/DESIGNER_10748989.pdf
   272513     24 -rw-r--r--   1 root     root        21691 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/ADVOCATE_10659182.pdf
   272530     20 -rw-r--r--   1 root     root        20368 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10228751.pdf
   272527     24 -rw-r--r--   1 root     root        22606 Sep 18 14:18 /content/resume-sreening-and-skill-matching-2/BANKING_10909673.pdf
   272589     28 -rw-r--r--   1 root     root        27910 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/BPO_11183737\ (1).pdf
   272582     20 -rw-r--r--   1 root     root        17801 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ARTS_11187796\ (1).pdf
   272604     28 -rw-r--r--   1 root     root        25581 Sep 18 14:23 /content/resume-sreening-and-skill-matching-2/ENGINEERING_10219099\ (1).pdf

In [ ]:
from pathlib import Path

resume_dir = Path("/content/resume-sreening-and-skill-matching-2/data/resumes")
resume_dir.mkdir(parents=True, exist_ok=True)

print("✅ Resume folder created:")
print(resume_dir)

✅ Resume folder created:
/content/resume-sreening-and-skill-matching-2/data/resumes

In [ ]:
!find /content/resume-sreening-and-skill-matching-2/data/resumes -type f | head -20

In [ ]:
!find /content/resume-sreening-and-skill-matching-2/data/resumes -type f | head -20

In [ ]:
%cd /content/resume-sreening-and-skill-matching-2

!python run_demo.py \
    --resumes_dir data/resumes \
    --job_description data/jd.txt \
    --top_k 10

/content/resume-sreening-and-skill-matching-2
2026-09-18 14:33:50,836 | INFO | Loading SBERT model 'all-mpnet-base-v2' on device 'cpu'
2026-09-18 14:33:51,122 | INFO | HTTP Request: GET https://huggingface.co/api/agent-harnesses "HTTP/1.1 200 OK"
2026-09-18 14:33:51,357 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:33:51,363 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-09-18 14:33:51,370 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
modules.json: 100% 349/349 [00:00<00:00, 969kB/s]
2026-09-18 14:33:51,609 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-18 14:33:51,610 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-18 14:33:51,615 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-09-18 14:33:51,622 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
config_sentence_transformers.json: 100% 116/116 [00:00<00:00, 296kB/s]
2026-09-18 14:33:51,624 | INFO | Loading SentenceTransformer model from sentence-transformers/all-mpnet-base-v2.
2026-09-18 14:33:51,854 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:33:51,860 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-09-18 14:33:52,092 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:33:52,098 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/README.md "HTTP/1.1 200 OK"
2026-09-18 14:33:52,104 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/README.md "HTTP/1.1 200 OK"
README.md: 100% 11.6k/11.6k [00:00<00:00, 18.0MB/s]
2026-09-18 14:33:52,338 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:33:52,344 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-09-18 14:33:52,576 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:33:52,582 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-09-18 14:33:52,589 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/sentence_bert_config.json "HTTP/1.1 200 OK"
sentence_bert_config.json: 100% 53.0/53.0 [00:00<00:00, 123kB/s]
2026-09-18 14:33:52,839 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:33:53,137 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:33:53,143 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 14:33:53,149 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
config.json: 100% 571/571 [00:00<00:00, 1.88MB/s]
2026-09-18 14:33:53,424 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:33:53,430 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 14:33:53,677 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/model.safetensors "HTTP/1.1 302 Found"
2026-09-18 14:33:53,986 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/xet-read-token/e8c3b32edf5434bc2275fc9bab85f82640a19130 "HTTP/1.1 200 OK"

model.safetensors: downloading bytes:  88% 385M/438M [00:03<00:00, 124MB/s, 30.8MB/s  ]
model.safetensors: reconstructing file:  58% 256M/438M [00:03<00:02, 65.5MB/s]
model.safetensors: downloading bytes:  94% 413M/438M [00:04<00:00, 130MB/s, 32.5MB/s  ]
model.safetensors: downloading bytes: 100% 414M/414M [00:07<00:00, 58.3MB/s, 33.7MB/s  ]
model.safetensors: reconstructing file: 100% 438M/438M [00:07<00:00, 61.6MB/s, 32.8MB/s  ]
Loading weights: 100% 199/199 [00:00<00:00, 4120.00it/s]
2026-09-18 14:34:01,679 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:34:01,905 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:34:02,153 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:34:02,393 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:34:02,624 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:34:02,631 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-18 14:34:02,641 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
tokenizer_config.json: 100% 363/363 [00:00<00:00, 1.07MB/s]
2026-09-18 14:34:02,888 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:34:02,895 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 14:34:03,149 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:34:03,155 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 14:34:03,389 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:34:03,395 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-18 14:34:03,632 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-09-18 14:34:03,870 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-09-18 14:34:04,115 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/vocab.txt "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:34:04,121 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/vocab.txt "HTTP/1.1 200 OK"
2026-09-18 14:34:04,129 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/vocab.txt "HTTP/1.1 200 OK"
vocab.txt: 100% 232k/232k [00:00<00:00, 52.9MB/s]
2026-09-18 14:34:04,375 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:34:04,381 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer.json "HTTP/1.1 200 OK"
2026-09-18 14:34:04,388 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer.json "HTTP/1.1 200 OK"
tokenizer.json: 100% 466k/466k [00:00<00:00, 83.5MB/s]
2026-09-18 14:34:04,629 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-09-18 14:34:04,870 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:34:04,876 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/special_tokens_map.json "HTTP/1.1 200 OK"
2026-09-18 14:34:04,883 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/special_tokens_map.json "HTTP/1.1 200 OK"
special_tokens_map.json: 100% 239/239 [00:00<00:00, 717kB/s]
2026-09-18 14:34:05,131 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-09-18 14:34:05,447 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:34:05,453 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-09-18 14:34:05,461 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
config.json: 100% 190/190 [00:00<00:00, 559kB/s]
2026-09-18 14:34:05,699 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2 "HTTP/1.1 200 OK"

======================================================================
          RESUME MATCHING & SELECTION SYSTEM
======================================================================

Indexing resumes from: data/resumes
2026-09-18 14:34:05,706 | INFO | Ingested 0/0 resumes successfully
2026-09-18 14:34:05,706 | INFO | 0 resumes parsed, 0 failed
Indexed: 0  Failed: 0
Performance: {}
Traceback (most recent call last):
  File "/content/resume-sreening-and-skill-matching-2/run_demo.py", line 316, in <module>
    main()
    ~~~~^^
  File "/content/resume-sreening-and-skill-matching-2/run_demo.py", line 244, in main
    ranked = pipeline.match(
        job_description_text=jd_text,
    ...<3 lines>...
        min_education=args.min_education,
    )
  File "/content/resume-sreening-and-skill-matching-2/src/pipeline.py", line 89, in match
    raise RuntimeError("No resumes indexed yet. Call index_directory() first.")
RuntimeError: No resumes indexed yet. Call index_directory() first.

In [ ]:
!find /content/resume-sreening-and-skill-matching-2/data/resumes -type f

In [ ]:
!ls -lah /content/resume-sreening-and-skill-matching-2/data/resumes

total 8.0K
drwxr-xr-x 2 root root 4.0K Sep 18 14:25 .
drwxr-xr-x 3 root root 4.0K Sep 18 14:25 ..

In [ ]:
from google.colab import files

uploaded = files.upload()

print("\nUploaded resumes:")
for filename in uploaded.keys():
    print("✅", filename)

Saving ACCOUNTANT_10554236.pdf to ACCOUNTANT_10554236 (2).pdf
Saving ACCOUNTANT_10674770.pdf to ACCOUNTANT_10674770 (2).pdf
Saving ACCOUNTANT_11163645.pdf to ACCOUNTANT_11163645 (2).pdf
Saving adhhul.pdf to adhhul (2).pdf
Saving ADVOCATE_10186968.pdf to ADVOCATE_10186968 (2).pdf
Saving ADVOCATE_10344379.pdf to ADVOCATE_10344379 (2).pdf
Saving ADVOCATE_10659182.pdf to ADVOCATE_10659182 (2).pdf
Saving AGRICULTURE_10953078.pdf to AGRICULTURE_10953078 (2).pdf
Saving AGRICULTURE_11197262.pdf to AGRICULTURE_11197262 (2).pdf
Saving althaf.docx to althaf (2).docx
Saving AlthafMohammadBabu_Resume.docx to AlthafMohammadBabu_Resume (2).docx
Saving APPAREL_10182582.pdf to APPAREL_10182582 (2).pdf
Saving APPAREL_10562768.pdf to APPAREL_10562768 (2).pdf
Saving ARTS_10830646.pdf to ARTS_10830646 (2).pdf
Saving ARTS_11187796.pdf to ARTS_11187796 (2).pdf
Saving AUTOMOBILE_11152490.pdf to AUTOMOBILE_11152490 (2).pdf
Saving AUTOMOBILE_11257723.pdf to AUTOMOBILE_11257723 (2).pdf
Saving AVIATION_10176815.pdf to AVIATION_10176815 (2).pdf
Saving AVIATION_10189110.pdf to AVIATION_10189110 (2).pdf
Saving BANKING_10329506.pdf to BANKING_10329506 (2).pdf
Saving BANKING_10909673.pdf to BANKING_10909673 (2).pdf
Saving BPO_11183737.pdf to BPO_11183737 (2).pdf
Saving BPO_13964744.pdf to BPO_13964744 (2).pdf
Saving BUSINESS-DEVELOPMENT_10228751.pdf to BUSINESS-DEVELOPMENT_10228751 (2).pdf
Saving BUSINESS-DEVELOPMENT_10235211.pdf to BUSINESS-DEVELOPMENT_10235211 (2).pdf
Saving CHEF_10001727.pdf to CHEF_10001727 (2).pdf
Saving CHEF_10276858.pdf to CHEF_10276858 (2).pdf
Saving CONSTRUCTION_10041713.pdf to CONSTRUCTION_10041713 (2).pdf
Saving CONSTRUCTION_10100240.pdf to CONSTRUCTION_10100240 (2).pdf
Saving CONSULTANT_10332998.pdf to CONSULTANT_10332998 (2).pdf
Saving CONSULTANT_10984392.pdf to CONSULTANT_10984392 (2).pdf
Saving DESIGNER_10466583.pdf to DESIGNER_10466583 (2).pdf
Saving DESIGNER_10748989.pdf to DESIGNER_10748989 (2).pdf
Saving DIGITAL-MEDIA_10005171.pdf to DIGITAL-MEDIA_10005171 (2).pdf
Saving DIGITAL-MEDIA_10515955.pdf to DIGITAL-MEDIA_10515955 (2).pdf
Saving ENGINEERING_10030015.pdf to ENGINEERING_10030015 (2).pdf
Saving ENGINEERING_10219099.pdf to ENGINEERING_10219099 (2).pdf
Saving FINANCE_10549585.pdf to FINANCE_10549585 (2).pdf
Saving FINANCE_11441764.pdf to FINANCE_11441764 (2).pdf
Saving FITNESS_10235429.pdf to FITNESS_10235429 (2).pdf
Saving FITNESS_10268614.pdf to FITNESS_10268614 (2).pdf
Saving HEALTHCARE_10062724.pdf to HEALTHCARE_10062724 (2).pdf
Saving HEALTHCARE_10076271.pdf to HEALTHCARE_10076271 (2).pdf
Saving HR_10399912.pdf to HR_10399912 (2).pdf
Saving HR_10694288.pdf to HR_10694288 (2).pdf
Saving INFORMATION-TECHNOLOGY_10089434.pdf to INFORMATION-TECHNOLOGY_10089434 (2).pdf
Saving INFORMATION-TECHNOLOGY_10247517.pdf to INFORMATION-TECHNOLOGY_10247517 (2).pdf
Saving PUBLIC-RELATIONS_10070224.pdf to PUBLIC-RELATIONS_10070224 (2).pdf
Saving PUBLIC-RELATIONS_10554045.pdf to PUBLIC-RELATIONS_10554045 (2).pdf
Saving rahul.pdf to rahul (2).pdf
Saving ramesh.pdf to ramesh (2).pdf
Saving SALES_10138632.pdf to SALES_10138632 (2).pdf
Saving SALES_10464113.pdf to SALES_10464113 (2).pdf
Saving sam.pdf to sam (2).pdf
Saving samantha.pdf to samantha (2).pdf
Saving shifa.pdf to shifa (2).pdf
Saving sinu.pdf to sinu (2).pdf
Saving susan.pdf to susan (2).pdf
Saving TEACHER_10504237.pdf to TEACHER_10504237 (2).pdf
Saving TEACHER_10527994.pdf to TEACHER_10527994 (2).pdf
Saving wikki.pdf to wikki (2).pdf

Uploaded resumes:
✅ ACCOUNTANT_10554236 (2).pdf
✅ ACCOUNTANT_10674770 (2).pdf
✅ ACCOUNTANT_11163645 (2).pdf
✅ adhhul (2).pdf
✅ ADVOCATE_10186968 (2).pdf
✅ ADVOCATE_10344379 (2).pdf
✅ ADVOCATE_10659182 (2).pdf
✅ AGRICULTURE_10953078 (2).pdf
✅ AGRICULTURE_11197262 (2).pdf
✅ althaf (2).docx
✅ AlthafMohammadBabu_Resume (2).docx
✅ APPAREL_10182582 (2).pdf
✅ APPAREL_10562768 (2).pdf
✅ ARTS_10830646 (2).pdf
✅ ARTS_11187796 (2).pdf
✅ AUTOMOBILE_11152490 (2).pdf
✅ AUTOMOBILE_11257723 (2).pdf
✅ AVIATION_10176815 (2).pdf
✅ AVIATION_10189110 (2).pdf
✅ BANKING_10329506 (2).pdf
✅ BANKING_10909673 (2).pdf
✅ BPO_11183737 (2).pdf
✅ BPO_13964744 (2).pdf
✅ BUSINESS-DEVELOPMENT_10228751 (2).pdf
✅ BUSINESS-DEVELOPMENT_10235211 (2).pdf
✅ CHEF_10001727 (2).pdf
✅ CHEF_10276858 (2).pdf
✅ CONSTRUCTION_10041713 (2).pdf
✅ CONSTRUCTION_10100240 (2).pdf
✅ CONSULTANT_10332998 (2).pdf
✅ CONSULTANT_10984392 (2).pdf
✅ DESIGNER_10466583 (2).pdf
✅ DESIGNER_10748989 (2).pdf
✅ DIGITAL-MEDIA_10005171 (2).pdf
✅ DIGITAL-MEDIA_10515955 (2).pdf
✅ ENGINEERING_10030015 (2).pdf
✅ ENGINEERING_10219099 (2).pdf
✅ FINANCE_10549585 (2).pdf
✅ FINANCE_11441764 (2).pdf
✅ FITNESS_10235429 (2).pdf
✅ FITNESS_10268614 (2).pdf
✅ HEALTHCARE_10062724 (2).pdf
✅ HEALTHCARE_10076271 (2).pdf
✅ HR_10399912 (2).pdf
✅ HR_10694288 (2).pdf
✅ INFORMATION-TECHNOLOGY_10089434 (2).pdf
✅ INFORMATION-TECHNOLOGY_10247517 (2).pdf
✅ PUBLIC-RELATIONS_10070224 (2).pdf
✅ PUBLIC-RELATIONS_10554045 (2).pdf
✅ rahul (2).pdf
✅ ramesh (2).pdf
✅ SALES_10138632 (2).pdf
✅ SALES_10464113 (2).pdf
✅ sam (2).pdf
✅ samantha (2).pdf
✅ shifa (2).pdf
✅ sinu (2).pdf
✅ susan (2).pdf
✅ TEACHER_10504237 (2).pdf
✅ TEACHER_10527994 (2).pdf
✅ wikki (2).pdf

In [ ]:
print("Number of files:", len(uploaded))
print("First few files:")

for filename in list(uploaded.keys())[:10]:
    print(filename)

Number of files: 61
First few files:
ACCOUNTANT_10554236 (2).pdf
ACCOUNTANT_10674770 (2).pdf
ACCOUNTANT_11163645 (2).pdf
adhhul (2).pdf
ADVOCATE_10186968 (2).pdf
ADVOCATE_10344379 (2).pdf
ADVOCATE_10659182 (2).pdf
AGRICULTURE_10953078 (2).pdf
AGRICULTURE_11197262 (2).pdf
althaf (2).docx

In [ ]:
from pathlib import Path
import shutil

project_dir = Path("/content/resume-sreening-and-skill-matching-2")
resume_dir = project_dir / "data" / "resumes"
resume_dir.mkdir(parents=True, exist_ok=True)

moved = 0

for filename in uploaded.keys():
    source = Path("/content") / filename
    destination = resume_dir / Path(filename).name

    if source.exists():
        shutil.move(str(source), str(destination))
        moved += 1

print(f"✅ Moved {moved} resume files")

✅ Moved 0 resume files

In [ ]:
!find /content/resume-sreening-and-skill-matching-2/data/resumes -type f | wc -l

0

In [ ]:
print("Uploaded files:")
for filename in uploaded.keys():
    print(repr(filename))

Uploaded files:
'ACCOUNTANT_10554236 (2).pdf'
'ACCOUNTANT_10674770 (2).pdf'
'ACCOUNTANT_11163645 (2).pdf'
'adhhul (2).pdf'
'ADVOCATE_10186968 (2).pdf'
'ADVOCATE_10344379 (2).pdf'
'ADVOCATE_10659182 (2).pdf'
'AGRICULTURE_10953078 (2).pdf'
'AGRICULTURE_11197262 (2).pdf'
'althaf (2).docx'
'AlthafMohammadBabu_Resume (2).docx'
'APPAREL_10182582 (2).pdf'
'APPAREL_10562768 (2).pdf'
'ARTS_10830646 (2).pdf'
'ARTS_11187796 (2).pdf'
'AUTOMOBILE_11152490 (2).pdf'
'AUTOMOBILE_11257723 (2).pdf'
'AVIATION_10176815 (2).pdf'
'AVIATION_10189110 (2).pdf'
'BANKING_10329506 (2).pdf'
'BANKING_10909673 (2).pdf'
'BPO_11183737 (2).pdf'
'BPO_13964744 (2).pdf'
'BUSINESS-DEVELOPMENT_10228751 (2).pdf'
'BUSINESS-DEVELOPMENT_10235211 (2).pdf'
'CHEF_10001727 (2).pdf'
'CHEF_10276858 (2).pdf'
'CONSTRUCTION_10041713 (2).pdf'
'CONSTRUCTION_10100240 (2).pdf'
'CONSULTANT_10332998 (2).pdf'
'CONSULTANT_10984392 (2).pdf'
'DESIGNER_10466583 (2).pdf'
'DESIGNER_10748989 (2).pdf'
'DIGITAL-MEDIA_10005171 (2).pdf'
'DIGITAL-MEDIA_10515955 (2).pdf'
'ENGINEERING_10030015 (2).pdf'
'ENGINEERING_10219099 (2).pdf'
'FINANCE_10549585 (2).pdf'
'FINANCE_11441764 (2).pdf'
'FITNESS_10235429 (2).pdf'
'FITNESS_10268614 (2).pdf'
'HEALTHCARE_10062724 (2).pdf'
'HEALTHCARE_10076271 (2).pdf'
'HR_10399912 (2).pdf'
'HR_10694288 (2).pdf'
'INFORMATION-TECHNOLOGY_10089434 (2).pdf'
'INFORMATION-TECHNOLOGY_10247517 (2).pdf'
'PUBLIC-RELATIONS_10070224 (2).pdf'
'PUBLIC-RELATIONS_10554045 (2).pdf'
'rahul (2).pdf'
'ramesh (2).pdf'
'SALES_10138632 (2).pdf'
'SALES_10464113 (2).pdf'
'sam (2).pdf'
'samantha (2).pdf'
'shifa (2).pdf'
'sinu (2).pdf'
'susan (2).pdf'
'TEACHER_10504237 (2).pdf'
'TEACHER_10527994 (2).pdf'
'wikki (2).pdf'

In [ ]:
!find /content -type f \( -iname "*.pdf" -o -iname "*.docx" \) | head -100

/content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10515955 (1).pdf
/content/resume-sreening-and-skill-matching-2/APPAREL_10562768.pdf
/content/resume-sreening-and-skill-matching-2/FITNESS_10235429 (1).pdf
/content/resume-sreening-and-skill-matching-2/BANKING_10909673 (2).pdf
/content/resume-sreening-and-skill-matching-2/AGRICULTURE_10953078.pdf
/content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10674770.pdf
/content/resume-sreening-and-skill-matching-2/INFORMATION-TECHNOLOGY_10247517.pdf
/content/resume-sreening-and-skill-matching-2/sam (1).pdf
/content/resume-sreening-and-skill-matching-2/TEACHER_10504237 (1).pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10344379.pdf
/content/resume-sreening-and-skill-matching-2/SALES_10138632 (2).pdf
/content/resume-sreening-and-skill-matching-2/HEALTHCARE_10062724 (1).pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10186968 (2).pdf
/content/resume-sreening-and-skill-matching-2/FINANCE_10549585 (1).pdf
/content/resume-sreening-and-skill-matching-2/sinu (1).pdf
/content/resume-sreening-and-skill-matching-2/BPO_11183737 (2).pdf
/content/resume-sreening-and-skill-matching-2/AlthafMohammadBabu_Resume (2).docx
/content/resume-sreening-and-skill-matching-2/ENGINEERING_10219099.pdf
/content/resume-sreening-and-skill-matching-2/ENGINEERING_10030015.pdf
/content/resume-sreening-and-skill-matching-2/HR_10399912 (2).pdf
/content/resume-sreening-and-skill-matching-2/sinu.pdf
/content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10070224 (2).pdf
/content/resume-sreening-and-skill-matching-2/BPO_11183737.pdf
/content/resume-sreening-and-skill-matching-2/AGRICULTURE_11197262 (1).pdf
/content/resume-sreening-and-skill-matching-2/BANKING_10329506 (2).pdf
/content/resume-sreening-and-skill-matching-2/BPO_13964744 (2).pdf
/content/resume-sreening-and-skill-matching-2/FINANCE_10549585 (2).pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10332998.pdf
/content/resume-sreening-and-skill-matching-2/wikki (2).pdf
/content/resume-sreening-and-skill-matching-2/samantha (2).pdf
/content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10041713 (1).pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10659182 (1).pdf
/content/resume-sreening-and-skill-matching-2/HR_10694288 (1).pdf
/content/resume-sreening-and-skill-matching-2/FINANCE_11441764 (2).pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10344379 (2).pdf
/content/resume-sreening-and-skill-matching-2/ENGINEERING_10030015 (2).pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10332998 (1).pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10984392 (1).pdf
/content/resume-sreening-and-skill-matching-2/BANKING_10329506 (1).pdf
/content/resume-sreening-and-skill-matching-2/HEALTHCARE_10076271 (2).pdf
/content/resume-sreening-and-skill-matching-2/althaf.docx
/content/resume-sreening-and-skill-matching-2/HEALTHCARE_10076271.pdf
/content/resume-sreening-and-skill-matching-2/ramesh (1).pdf
/content/resume-sreening-and-skill-matching-2/SALES_10464113 (2).pdf
/content/resume-sreening-and-skill-matching-2/HR_10694288.pdf
/content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10554236 (1).pdf
/content/resume-sreening-and-skill-matching-2/samantha (1).pdf
/content/resume-sreening-and-skill-matching-2/ARTS_11187796 (2).pdf
/content/resume-sreening-and-skill-matching-2/ramesh (2).pdf
/content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10041713.pdf
/content/resume-sreening-and-skill-matching-2/AGRICULTURE_11197262.pdf
/content/resume-sreening-and-skill-matching-2/INFORMATION-TECHNOLOGY_10247517 (2).pdf
/content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10228751 (1).pdf
/content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10228751 (2).pdf
/content/resume-sreening-and-skill-matching-2/DESIGNER_10748989 (2).pdf
/content/resume-sreening-and-skill-matching-2/susan.pdf
/content/resume-sreening-and-skill-matching-2/susan (2).pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10984392.pdf
/content/resume-sreening-and-skill-matching-2/AGRICULTURE_10953078 (2).pdf
/content/resume-sreening-and-skill-matching-2/ARTS_10830646.pdf
/content/resume-sreening-and-skill-matching-2/HR_10399912.pdf
/content/resume-sreening-and-skill-matching-2/CHEF_10001727 (2).pdf
/content/resume-sreening-and-skill-matching-2/TEACHER_10504237.pdf
/content/resume-sreening-and-skill-matching-2/APPAREL_10562768 (1).pdf
/content/resume-sreening-and-skill-matching-2/FITNESS_10235429.pdf
/content/resume-sreening-and-skill-matching-2/SALES_10138632 (1).pdf
/content/resume-sreening-and-skill-matching-2/APPAREL_10562768 (2).pdf
/content/resume-sreening-and-skill-matching-2/HR_10694288 (2).pdf
/content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10070224 (1).pdf
/content/resume-sreening-and-skill-matching-2/INFORMATION-TECHNOLOGY_10089434 (2).pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10984392 (2).pdf
/content/resume-sreening-and-skill-matching-2/SALES_10138632.pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10659182 (2).pdf
/content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10515955.pdf
/content/resume-sreening-and-skill-matching-2/samantha.pdf
/content/resume-sreening-and-skill-matching-2/BUSINESS-DEVELOPMENT_10235211.pdf
/content/resume-sreening-and-skill-matching-2/ACCOUNTANT_10674770 (2).pdf
/content/resume-sreening-and-skill-matching-2/rahul.pdf
/content/resume-sreening-and-skill-matching-2/HR_10399912 (1).pdf
/content/resume-sreening-and-skill-matching-2/SALES_10464113 (1).pdf
/content/resume-sreening-and-skill-matching-2/AVIATION_10189110 (2).pdf
/content/resume-sreening-and-skill-matching-2/TEACHER_10527994 (1).pdf
/content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10100240 (1).pdf
/content/resume-sreening-and-skill-matching-2/AVIATION_10189110.pdf
/content/resume-sreening-and-skill-matching-2/sam (2).pdf
/content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10554045 (2).pdf
/content/resume-sreening-and-skill-matching-2/AUTOMOBILE_11152490.pdf
/content/resume-sreening-and-skill-matching-2/AVIATION_10176815.pdf
/content/resume-sreening-and-skill-matching-2/DESIGNER_10466583.pdf
/content/resume-sreening-and-skill-matching-2/DIGITAL-MEDIA_10005171.pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10344379 (1).pdf
/content/resume-sreening-and-skill-matching-2/wikki (1).pdf
/content/resume-sreening-and-skill-matching-2/DESIGNER_10466583 (2).pdf
/content/resume-sreening-and-skill-matching-2/PUBLIC-RELATIONS_10070224.pdf
/content/resume-sreening-and-skill-matching-2/CONSULTANT_10332998 (2).pdf
/content/resume-sreening-and-skill-matching-2/CONSTRUCTION_10041713 (2).pdf
/content/resume-sreening-and-skill-matching-2/TEACHER_10504237 (2).pdf
/content/resume-sreening-and-skill-matching-2/AlthafMohammadBabu_Resume.docx
/content/resume-sreening-and-skill-matching-2/ACCOUNTANT_11163645 (2).pdf
/content/resume-sreening-and-skill-matching-2/ADVOCATE_10186968 (1).pdf

In [ ]:
from pathlib import Path
import shutil

project_dir = Path("/content/resume-sreening-and-skill-matching-2")
resume_dir = project_dir / "data" / "resumes"

resume_dir.mkdir(parents=True, exist_ok=True)

moved = 0

for pdf in project_dir.glob("*.pdf"):
    shutil.move(str(pdf), str(resume_dir / pdf.name))
    moved += 1

print(f"✅ Moved {moved} PDF files")

✅ Moved 177 PDF files

In [ ]:
!find /content/resume-sreening-and-skill-matching-2/data/resumes -type f -iname "*.pdf" | wc -l

177

In [ ]:
!find /content/resume-sreening-and-skill-matching-2/data/resumes -type f -iname "*.pdf" | head -10

/content/resume-sreening-and-skill-matching-2/data/resumes/DIGITAL-MEDIA_10515955 (1).pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/APPAREL_10562768.pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/FITNESS_10235429 (1).pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/BANKING_10909673 (2).pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/AGRICULTURE_10953078.pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/ACCOUNTANT_10674770.pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/INFORMATION-TECHNOLOGY_10247517.pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/sam (1).pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/TEACHER_10504237 (1).pdf
/content/resume-sreening-and-skill-matching-2/data/resumes/ADVOCATE_10344379.pdf

In [ ]:
%cd /content/resume-sreening-and-skill-matching-2

!python run_demo.py \
    --resumes_dir data/resumes \
    --job_description data/jd.txt \
    --top_k 10

/content/resume-sreening-and-skill-matching-2
2026-09-18 14:44:33,672 | INFO | Loading SBERT model 'all-mpnet-base-v2' on device 'cpu'
2026-09-18 14:44:33,966 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-18 14:44:33,967 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-18 14:44:33,974 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-09-18 14:44:34,204 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:34,210 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-09-18 14:44:34,211 | INFO | Loading SentenceTransformer model from sentence-transformers/all-mpnet-base-v2.
2026-09-18 14:44:34,451 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:34,457 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-09-18 14:44:34,684 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:34,691 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/README.md "HTTP/1.1 200 OK"
2026-09-18 14:44:34,937 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:34,943 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-09-18 14:44:35,180 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:35,188 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-09-18 14:44:35,427 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:44:35,653 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:35,659 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 14:44:35,915 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:35,921 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 199/199 [00:00<00:00, 3625.78it/s]
2026-09-18 14:44:36,403 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:44:36,638 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:44:36,885 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:44:37,120 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 14:44:37,351 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:37,357 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-18 14:44:37,589 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:37,596 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 14:44:37,832 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:37,840 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 14:44:38,089 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:38,097 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-18 14:44:38,349 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-09-18 14:44:38,601 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-09-18 14:44:38,934 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 14:44:38,940 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-09-18 14:44:39,187 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2 "HTTP/1.1 200 OK"

======================================================================
          RESUME MATCHING & SELECTION SYSTEM
======================================================================

Indexing resumes from: data/resumes
2026-09-18 14:47:08,171 | INFO | Ingested 177/177 resumes successfully
2026-09-18 14:47:08,172 | INFO | 177 resumes parsed, 0 failed
Batches: 100% 2/2 [04:48<00:00, 144.16s/it]
2026-09-18 14:51:58,347 | INFO | Encoded 150 texts in 288.37s (1.9225s/item) on cpu
2026-09-18 14:51:58,366 | INFO | Added 150 vectors. Index now holds 150 total.
2026-09-18 14:52:46,479 | INFO | Encoded 27 texts in 47.96s (1.7762s/item) on cpu
2026-09-18 14:52:46,480 | INFO | Added 27 vectors. Index now holds 177 total.
Indexed: 177  Failed: 0
Performance: {'mean_seconds_per_resume': 1.900173354096039, 'p95_seconds_per_resume': 1.9224935713266618, 'total_seconds': 336.3306836749989, 'resumes_per_second': 0.5262677733294105}
Batches: 100% 1/1 [00:00<00:00,  1.14it/s]

======================================================================
                    SCREENING RESULTS
======================================================================

Candidates analyzed: 177
Candidates displayed: 10

----------------------------------------------------------------------
Rank  Candidate           Score       Decision
----------------------------------------------------------------------
1     adhhul                78.4%     SELECTED
2     adhhul (2)            78.4%     SELECTED
3     adhhul (1)            78.4%     SELECTED
4     rahul (1)             76.1%     SELECTED
5     rahul (2)             76.1%     SELECTED
6     rahul                 76.1%     SELECTED
7     ramesh (2)            69.2%     REVIEW
8     ramesh                69.2%     REVIEW
9     ramesh (1)            69.2%     REVIEW
10    samantha              64.8%     REVIEW
----------------------------------------------------------------------

Excel report created successfully: resume_screening_results.xlsx

======================================================================
                  SCREENING COMPLETE
======================================================================

# Resume Screening and Skill Matching System

### AI-Based Resume Screening using Sentence-BERT and FAISS

This project automatically processes resumes and compares them against a given job description.

### Workflow
1. Resume ingestion
2. Text extraction and preprocessing
3. Semantic embedding using Sentence-BERT
4. FAISS vector indexing
5. Job description matching
6. Candidate ranking
7. Screening decision
8. Excel report generation

In [36]:
!find /content/resume-sreening-and-skill-matching-2 -type f -name "*.xlsx"

/content/resume-sreening-and-skill-matching-2/resume_screening_results.xlsx
/content/resume-sreening-and-skill-matching-2/resume-sreening-and-skill-matching-2/resume_screening_results.xlsx

In [37]:
from google.colab import files

report_path = "/content/resume-sreening-and-skill-matching-2/resume_screening_results.xlsx"

files.download(report_path)

To run

In [38]:
%cd /content/resume-sreening-and-skill-matching-2

!python run_demo.py \
    --resumes_dir data/resumes \
    --job_description data/jd.txt \
    --top_k 177

/content/resume-sreening-and-skill-matching-2
2026-09-18 15:13:40,961 | INFO | Loading SBERT model 'all-mpnet-base-v2' on device 'cpu'
2026-09-18 15:13:41,295 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-18 15:13:41,296 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-09-18 15:13:41,303 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-09-18 15:13:41,549 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:41,558 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-09-18 15:13:41,559 | INFO | Loading SentenceTransformer model from sentence-transformers/all-mpnet-base-v2.
2026-09-18 15:13:41,792 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:41,801 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-09-18 15:13:42,045 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:42,054 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/README.md "HTTP/1.1 200 OK"
2026-09-18 15:13:42,302 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:42,310 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-09-18 15:13:42,560 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:42,568 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-09-18 15:13:42,815 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-09-18 15:13:43,056 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:43,064 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 15:13:43,327 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:43,335 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 199/199 [00:00<00:00, 3534.51it/s]
2026-09-18 15:13:43,793 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 15:13:44,044 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 15:13:44,296 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 15:13:44,543 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-09-18 15:13:44,787 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:44,794 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-18 15:13:45,031 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:45,038 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 15:13:45,287 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:45,294 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-09-18 15:13:45,544 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:45,551 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-09-18 15:13:45,806 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-09-18 15:13:46,086 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-09-18 15:13:46,400 | INFO | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-09-18 15:13:46,407 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-09-18 15:13:46,656 | INFO | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2 "HTTP/1.1 200 OK"

======================================================================
          RESUME MATCHING & SELECTION SYSTEM
======================================================================

Indexing resumes from: data/resumes
2026-09-18 15:16:15,734 | INFO | Ingested 177/177 resumes successfully
2026-09-18 15:16:15,735 | INFO | 177 resumes parsed, 0 failed
Batches: 100% 2/2 [04:43<00:00, 141.72s/it]
2026-09-18 15:21:00,265 | INFO | Encoded 150 texts in 283.45s (1.8897s/item) on cpu
2026-09-18 15:21:00,267 | INFO | Added 150 vectors. Index now holds 150 total.
2026-09-18 15:21:47,915 | INFO | Encoded 27 texts in 47.58s (1.7622s/item) on cpu
2026-09-18 15:21:47,916 | INFO | Added 27 vectors. Index now holds 177 total.
Indexed: 177  Failed: 0
Performance: {'mean_seconds_per_resume': 1.8702387082598941, 'p95_seconds_per_resume': 1.889686479260005, 'total_seconds': 331.03225136200126, 'resumes_per_second': 0.534691104180182}
Batches: 100% 1/1 [00:00<00:00,  1.14it/s]

======================================================================
                    SCREENING RESULTS
======================================================================

Candidates analyzed: 177
Candidates displayed: 177

----------------------------------------------------------------------
Rank  Candidate           Score       Decision
----------------------------------------------------------------------
1     adhhul                78.4%     SELECTED
2     adhhul (2)            78.4%     SELECTED
3     adhhul (1)            78.4%     SELECTED
4     rahul                 76.1%     SELECTED
5     rahul (2)             76.1%     SELECTED
6     rahul (1)             76.1%     SELECTED
7     ramesh                69.2%     REVIEW
8     ramesh (2)            69.2%     REVIEW
9     ramesh (1)            69.2%     REVIEW
10    samantha              64.8%     REVIEW
11    samantha (1)          64.8%     REVIEW
12    samantha (2)          64.8%     REVIEW
13    BPO_13964744          36.9%     REJECTED
14    BPO_13964744 (2)      36.9%     REJECTED
15    BPO_13964744 (1)      36.9%     REJECTED
16    INFORMATION-TECHNOLOGY_10089434  35.4%     REJECTED
17    INFORMATION-TECHNOLOGY_10089434 (1)  35.4%     REJECTED
18    INFORMATION-TECHNOLOGY_10089434 (2)  35.4%     REJECTED
19    INFORMATION-TECHNOLOGY_10247517 (2)  33.6%     REJECTED
20    INFORMATION-TECHNOLOGY_10247517 (1)  33.6%     REJECTED
21    INFORMATION-TECHNOLOGY_10247517  33.6%     REJECTED
22    sam                   32.9%     REJECTED
23    sam (2)               32.9%     REJECTED
24    sam (1)               32.9%     REJECTED
25    AVIATION_10176815     32.0%     REJECTED
26    AVIATION_10176815 (1)  32.0%     REJECTED
27    AVIATION_10176815 (2)  32.0%     REJECTED
28    BUSINESS-DEVELOPMENT_10235211  30.3%     REJECTED
29    BUSINESS-DEVELOPMENT_10235211 (1)  30.3%     REJECTED
30    BUSINESS-DEVELOPMENT_10235211 (2)  30.3%     REJECTED
31    APPAREL_10562768      30.2%     REJECTED
32    APPAREL_10562768 (2)  30.2%     REJECTED
33    APPAREL_10562768 (1)  30.2%     REJECTED
34    AVIATION_10189110     29.6%     REJECTED
35    AVIATION_10189110 (2)  29.6%     REJECTED
36    AVIATION_10189110 (1)  29.6%     REJECTED
37    wikki (1)             28.7%     REJECTED
38    wikki                 28.7%     REJECTED
39    wikki (2)             28.7%     REJECTED
40    CONSTRUCTION_10041713  28.4%     REJECTED
41    CONSTRUCTION_10041713 (2)  28.4%     REJECTED
42    CONSTRUCTION_10041713 (1)  28.4%     REJECTED
43    ENGINEERING_10030015 (2)  27.1%     REJECTED
44    ENGINEERING_10030015 (1)  27.1%     REJECTED
45    ENGINEERING_10030015  27.1%     REJECTED
46    HR_10399912           26.8%     REJECTED
47    HR_10399912 (2)       26.8%     REJECTED
48    HR_10399912 (1)       26.8%     REJECTED
49    ENGINEERING_10219099 (2)  26.5%     REJECTED
50    ENGINEERING_10219099  26.5%     REJECTED
51    ENGINEERING_10219099 (1)  26.5%     REJECTED
52    BANKING_10329506      26.5%     REJECTED
53    BANKING_10329506 (2)  26.5%     REJECTED
54    BANKING_10329506 (1)  26.5%     REJECTED
55    sinu                  24.8%     REJECTED
56    sinu (2)              24.8%     REJECTED
57    sinu (1)              24.8%     REJECTED
58    FINANCE_10549585 (2)  24.6%     REJECTED
59    FINANCE_10549585      24.6%     REJECTED
60    FINANCE_10549585 (1)  24.6%     REJECTED
61    BANKING_10909673      24.5%     REJECTED
62    BANKING_10909673 (2)  24.5%     REJECTED
63    BANKING_10909673 (1)  24.5%     REJECTED
64    ADVOCATE_10344379     24.3%     REJECTED
65    ADVOCATE_10344379 (2)  24.3%     REJECTED
66    ADVOCATE_10344379 (1)  24.3%     REJECTED
67    CONSULTANT_10984392 (2)  23.9%     REJECTED
68    CONSULTANT_10984392   23.9%     REJECTED
69    CONSULTANT_10984392 (1)  23.9%     REJECTED
70    susan (2)             23.6%     REJECTED
71    susan                 23.6%     REJECTED
72    susan (1)             23.6%     REJECTED
73    FINANCE_11441764      23.6%     REJECTED
74    FINANCE_11441764 (2)  23.6%     REJECTED
75    FINANCE_11441764 (1)  23.6%     REJECTED
76    shifa (1)             23.5%     REJECTED
77    shifa                 23.5%     REJECTED
78    shifa (2)             23.5%     REJECTED
79    DIGITAL-MEDIA_10515955 (2)  23.5%     REJECTED
80    DIGITAL-MEDIA_10515955  23.5%     REJECTED
81    DIGITAL-MEDIA_10515955 (1)  23.5%     REJECTED
82    BPO_11183737          23.4%     REJECTED
83    BPO_11183737 (1)      23.4%     REJECTED
84    BPO_11183737 (2)      23.4%     REJECTED
85    CONSULTANT_10332998 (2)  23.3%     REJECTED
86    CONSULTANT_10332998   23.3%     REJECTED
87    CONSULTANT_10332998 (1)  23.3%     REJECTED
88    ARTS_10830646 (2)     23.1%     REJECTED
89    ARTS_10830646         23.1%     REJECTED
90    ARTS_10830646 (1)     23.1%     REJECTED
91    BUSINESS-DEVELOPMENT_10228751  23.0%     REJECTED
92    BUSINESS-DEVELOPMENT_10228751 (2)  23.0%     REJECTED
93    BUSINESS-DEVELOPMENT_10228751 (1)  23.0%     REJECTED
94    AUTOMOBILE_11257723   22.9%     REJECTED
95    AUTOMOBILE_11257723 (2)  22.9%     REJECTED
96    AUTOMOBILE_11257723 (1)  22.9%     REJECTED
97    ACCOUNTANT_11163645   22.8%     REJECTED
98    ACCOUNTANT_11163645 (1)  22.8%     REJECTED
99    ACCOUNTANT_11163645 (2)  22.8%     REJECTED
100   ARTS_11187796         22.5%     REJECTED
101   ARTS_11187796 (2)     22.5%     REJECTED
102   ARTS_11187796 (1)     22.5%     REJECTED
103   APPAREL_10182582      22.4%     REJECTED
104   APPAREL_10182582 (1)  22.4%     REJECTED
105   APPAREL_10182582 (2)  22.4%     REJECTED
106   DESIGNER_10748989     22.0%     REJECTED
107   DESIGNER_10748989 (2)  22.0%     REJECTED
108   DESIGNER_10748989 (1)  22.0%     REJECTED
109   PUBLIC-RELATIONS_10554045  21.3%     REJECTED
110   PUBLIC-RELATIONS_10554045 (2)  21.3%     REJECTED
111   PUBLIC-RELATIONS_10554045 (1)  21.3%     REJECTED
112   TEACHER_10527994      21.2%     REJECTED
113   TEACHER_10527994 (2)  21.2%     REJECTED
114   TEACHER_10527994 (1)  21.2%     REJECTED
115   ADVOCATE_10659182     21.1%     REJECTED
116   ADVOCATE_10659182 (1)  21.1%     REJECTED
117   ADVOCATE_10659182 (2)  21.1%     REJECTED
118   CONSTRUCTION_10100240 (1)  20.4%     REJECTED
119   CONSTRUCTION_10100240  20.4%     REJECTED
120   CONSTRUCTION_10100240 (2)  20.4%     REJECTED
121   ADVOCATE_10186968 (2)  19.8%     REJECTED
122   ADVOCATE_10186968     19.8%     REJECTED
123   ADVOCATE_10186968 (1)  19.8%     REJECTED
124   SALES_10464113        19.1%     REJECTED
125   SALES_10464113 (2)    19.1%     REJECTED
126   SALES_10464113 (1)    19.1%     REJECTED
127   SALES_10138632        18.4%     REJECTED
128   SALES_10138632 (2)    18.4%     REJECTED
129   SALES_10138632 (1)    18.4%     REJECTED
130   CHEF_10276858         18.0%     REJECTED
131   CHEF_10276858 (2)     18.0%     REJECTED
132   CHEF_10276858 (1)     18.0%     REJECTED
133   CHEF_10001727 (2)     17.9%     REJECTED
134   CHEF_10001727         17.9%     REJECTED
135   CHEF_10001727 (1)     17.9%     REJECTED
136   FITNESS_10235429      17.8%     REJECTED
137   FITNESS_10235429 (1)  17.8%     REJECTED
138   FITNESS_10235429 (2)  17.8%     REJECTED
139   ACCOUNTANT_10554236   17.2%     REJECTED
140   ACCOUNTANT_10554236 (1)  17.2%     REJECTED
141   ACCOUNTANT_10554236 (2)  17.2%     REJECTED
142   HR_10694288           16.4%     REJECTED
143   HR_10694288 (2)       16.4%     REJECTED
144   HR_10694288 (1)       16.4%     REJECTED
145   PUBLIC-RELATIONS_10070224  15.8%     REJECTED
146   PUBLIC-RELATIONS_10070224 (1)  15.8%     REJECTED
147   PUBLIC-RELATIONS_10070224 (2)  15.8%     REJECTED
148   AUTOMOBILE_11152490 (1)  15.5%     REJECTED
149   AUTOMOBILE_11152490   15.5%     REJECTED
150   AUTOMOBILE_11152490 (2)  15.5%     REJECTED
151   HEALTHCARE_10076271 (1)  14.8%     REJECTED
152   HEALTHCARE_10076271 (2)  14.8%     REJECTED
153   HEALTHCARE_10076271   14.8%     REJECTED
154   AGRICULTURE_10953078 (2)  13.4%     REJECTED
155   AGRICULTURE_10953078  13.4%     REJECTED
156   AGRICULTURE_10953078 (1)  13.4%     REJECTED
157   DESIGNER_10466583 (1)  13.2%     REJECTED
158   DESIGNER_10466583     13.2%     REJECTED
159   DESIGNER_10466583 (2)  13.2%     REJECTED
160   TEACHER_10504237      12.8%     REJECTED
161   TEACHER_10504237 (1)  12.8%     REJECTED
162   TEACHER_10504237 (2)  12.8%     REJECTED
163   HEALTHCARE_10062724   11.8%     REJECTED
164   HEALTHCARE_10062724 (2)  11.8%     REJECTED
165   HEALTHCARE_10062724 (1)  11.8%     REJECTED
166   ACCOUNTANT_10674770 (1)  11.4%     REJECTED
167   ACCOUNTANT_10674770   11.4%     REJECTED
168   ACCOUNTANT_10674770 (2)  11.4%     REJECTED
169   FITNESS_10268614 (2)  11.3%     REJECTED
170   FITNESS_10268614      11.3%     REJECTED
171   FITNESS_10268614 (1)  11.3%     REJECTED
172   DIGITAL-MEDIA_10005171  11.0%     REJECTED
173   DIGITAL-MEDIA_10005171 (2)  11.0%     REJECTED
174   DIGITAL-MEDIA_10005171 (1)  11.0%     REJECTED
175   AGRICULTURE_11197262 (2)   4.7%     REJECTED
176   AGRICULTURE_11197262   4.7%     REJECTED
177   AGRICULTURE_11197262 (1)   4.7%     REJECTED
----------------------------------------------------------------------

Excel report created successfully: resume_screening_results.xlsx

======================================================================
                  SCREENING COMPLETE
======================================================================

To create excel

In [39]:
import pandas as pd

report_path = "/content/resume-sreening-and-skill-matching-2/resume_screening_results.xlsx"

results = pd.read_excel(report_path)

print("Number of candidates in report:", len(results))

display(results)

Number of candidates in report: 177

,Rank,Resume File,Overall Match Score,Semantic Match,Skill Match,Decision,Reason,Matched Skills,Missing Skills,Experience,Education
0,1,adhhul,78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
1,2,adhhul (2),78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
2,3,adhhul (1),78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
3,4,rahul,76.06,78.99,69.23,SELECTED,Strong overall match with the job description.,"azure, docker, gcp, kubernetes, machine learni...","aws, communication, deep learning, tensorflow",7.0,Masters
4,5,rahul (2),76.06,78.99,69.23,SELECTED,Strong overall match with the job description.,"azure, docker, gcp, kubernetes, machine learni...","aws, communication, deep learning, tensorflow",7.0,Masters
...,...,...,...,...,...,...,...,...,...,...,...
172,173,DIGITAL-MEDIA_10005171 (2),10.99,15.70,0.00,REJECTED,Low overall match with the job description.,NaN,"aws, azure, communication, deep learning, dock...",NaN,High School
173,174,DIGITAL-MEDIA_10005171 (1),10.99,15.70,0.00,REJECTED,Low overall match with the job description.,NaN,"aws, azure, communication, deep learning, dock...",NaN,High School
174,175,AGRICULTURE_11197262 (2),4.65,3.35,7.69,REJECTED,Low overall match with the job description.,communication,"aws, azure, deep learning, docker, gcp, kubern...",NaN,Masters
175,176,AGRICULTURE_11197262,4.65,3.35,7.69,REJECTED,Low overall match with the job description.,communication,"aws, azure, deep learning, docker, gcp, kubern...",NaN,Masters
176,177,AGRICULTURE_11197262 (1),4.65,3.35,7.69,REJECTED,Low overall match with the job description.,communication,"aws, azure, deep learning, docker, gcp, kubern...",NaN,Masters

In [40]:
display(results.head(10))

,Rank,Resume File,Overall Match Score,Semantic Match,Skill Match,Decision,Reason,Matched Skills,Missing Skills,Experience,Education
0,1,adhhul,78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
1,2,adhhul (2),78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
2,3,adhhul (1),78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
3,4,rahul,76.06,78.99,69.23,SELECTED,Strong overall match with the job description.,"azure, docker, gcp, kubernetes, machine learni...","aws, communication, deep learning, tensorflow",7.0,Masters
4,5,rahul (2),76.06,78.99,69.23,SELECTED,Strong overall match with the job description.,"azure, docker, gcp, kubernetes, machine learni...","aws, communication, deep learning, tensorflow",7.0,Masters
5,6,rahul (1),76.06,78.99,69.23,SELECTED,Strong overall match with the job description.,"azure, docker, gcp, kubernetes, machine learni...","aws, communication, deep learning, tensorflow",7.0,Masters
6,7,ramesh,69.25,72.55,61.54,REVIEW,Moderate match. Recruiter should review the ca...,"aws, docker, kubernetes, machine learning, nlp...","azure, communication, deep learning, gcp, tens...",NaN,Masters
7,8,ramesh (2),69.25,72.55,61.54,REVIEW,Moderate match. Recruiter should review the ca...,"aws, docker, kubernetes, machine learning, nlp...","azure, communication, deep learning, gcp, tens...",NaN,Masters
8,9,ramesh (1),69.25,72.55,61.54,REVIEW,Moderate match. Recruiter should review the ca...,"aws, docker, kubernetes, machine learning, nlp...","azure, communication, deep learning, gcp, tens...",NaN,Masters
9,10,samantha,64.84,69.55,53.85,REVIEW,Moderate match. Recruiter should review the ca...,"aws, docker, kubernetes, machine learning, pyt...","azure, communication, deep learning, gcp, nlp,...",NaN,Bachelors

## Screening Results

The system processed the resumes and ranked candidates based on their similarity to the provided job description.

The results include semantic similarity, skill overlap, overall match score, matched skills, missing skills, experience, education, and screening decision.

In [41]:
import pandas as pd

report_path = "/content/resume-sreening-and-skill-matching-2/resume_screening_results.xlsx"

results = pd.read_excel(report_path)

print(f"Total candidates processed: {len(results)}")

display(results)

Total candidates processed: 177

,Rank,Resume File,Overall Match Score,Semantic Match,Skill Match,Decision,Reason,Matched Skills,Missing Skills,Experience,Education
0,1,adhhul,78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
1,2,adhhul (2),78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
2,3,adhhul (1),78.38,79.01,76.92,SELECTED,Strong overall match with the job description.,"azure, deep learning, docker, kubernetes, mach...","aws, communication, gcp",9.0,Masters
3,4,rahul,76.06,78.99,69.23,SELECTED,Strong overall match with the job description.,"azure, docker, gcp, kubernetes, machine learni...","aws, communication, deep learning, tensorflow",7.0,Masters
4,5,rahul (2),76.06,78.99,69.23,SELECTED,Strong overall match with the job description.,"azure, docker, gcp, kubernetes, machine learni...","aws, communication, deep learning, tensorflow",7.0,Masters
...,...,...,...,...,...,...,...,...,...,...,...
172,173,DIGITAL-MEDIA_10005171 (2),10.99,15.70,0.00,REJECTED,Low overall match with the job description.,NaN,"aws, azure, communication, deep learning, dock...",NaN,High School
173,174,DIGITAL-MEDIA_10005171 (1),10.99,15.70,0.00,REJECTED,Low overall match with the job description.,NaN,"aws, azure, communication, deep learning, dock...",NaN,High School
174,175,AGRICULTURE_11197262 (2),4.65,3.35,7.69,REJECTED,Low overall match with the job description.,communication,"aws, azure, deep learning, docker, gcp, kubern...",NaN,Masters
175,176,AGRICULTURE_11197262,4.65,3.35,7.69,REJECTED,Low overall match with the job description.,communication,"aws, azure, deep learning, docker, gcp, kubern...",NaN,Masters
176,177,AGRICULTURE_11197262 (1),4.65,3.35,7.69,REJECTED,Low overall match with the job description.,communication,"aws, azure, deep learning, docker, gcp, kubern...",NaN,Masters

## Download Screening Report

The complete screening results are available as an Excel report.

In [42]:
from google.colab import files

files.download(
    "/content/resume-sreening-and-skill-matching-2/resume_screening_results.xlsx"
)